### ISSUE TITLE
textlint --init support plugin

### ISSUE THREAD

**Issue by azu** [textlint/textlint#1037]
```bash
$ npm install textlint textlint-plugin-html textlint-rule-preset-ja-technical-writing
$ npx textlint --init
```

It should generate following `.textlintrc.json`:

```json
{
  "plugins": [
    "html"
  ],
  "filters": {},
  "rules": {
    "preset-ja-technical-writing": true
  }
}
```

or 

```json
{
  "plugins": {
    "html": true
  },
  "filters": {},
  "rules": {
    "preset-ja-technical-writing": true
  }
}
```

I like the latter.

However, current implementaion does not support plugin:

```json
{
  "filters": {},
  "rules": {
    "preset-ja-technical-writing": true
  }
}
```

## TODO

- [ ] support `"html"` property on --init
  - https://github.com/textlint/textlint/blob/master/packages/textlint/src/config/config-initializer.ts

**Comment by chick-p** [comment]
@azu 
I created a pull request #1039
Please review it.
