### ISSUE TITLE
Not all tests in textlint have been run

### ISSUE THREAD

**Issue by takmatsukawa** [textlint/textlint#1041]
**What version of textlint are you using?**

4251c9e

**What file type (Markdown, plain text, etc.) are you using?**

**What did you do? Please include the actual source code causing the issue.**

I followed the [Development Workflow
](https://github.com/textlint/textlint/blob/master/docs/CONTRIBUTING.md#development-workflow), added a new test in config-initializer-test.ts and `npm run test` in `packages/textlint`.

**What did you expect to happen?**

**What actually happened? Please include the actual, raw output from textlint.**

 The test I added never failed.

I found mocha's `.only()` is used [here](https://github.com/textlint/textlint/blob/master/packages/textlint/test/textlint-core/textlint-core-test.ts#L58). According to [mocha's doc](https://mochajs.org/#exclusive-tests
), It forces only its specified tests to be executed. 
After removing the `.only`, some tests failed.

**Comment by azu** [comment]
Ah, It `.only` should beremoved.

**Comment by azu** [comment]
It related with Dynamic Import + .ts

Dynamic import can not import .ts file by default.
Probably, loader: ts-node/esm is required.

**Comment by azu** [comment]
We need to add https://github.com/lo1tuma/eslint-plugin-mocha for preventing this issue.

- maybe related #685

**Comment by takmatsukawa** [comment]
Good work! Additionally, we can use `mocha --forbid-only` option.

> Be mindful not to commit usages of .only() to version control, unless you really mean it! To do so one can run mocha with the option --forbid-only in the continuous integration test command (or in a git precommit hook).

The option will make the executions of tests containing `.only` fail.

**Comment by azu** [comment]
It may difficutlt to use `--forbid-only`.
We want to use only `--forbid-only` on CI.

```
if process.env.CI 
  mocha --forbid-only 
else 
  mocha
```

`.mocharrc.js` will resolve it, but I not want to use dynamic config.
(It make migration difficult)

I want to write like this.

```
MOCHA_FORBIT_ONLY=1 mocha
```

**Comment by takmatsukawa** [comment]
I found an example like this:

.mocharc.js

```js
'use strict';

module.exports = {
  'forbid-only': Boolean(process.env.CI)
};
```

I'm not sure it works in this repo.

**Comment by azu** [comment]
> .mocharrc.js will resolve it, but I not want to use dynamic config.
> (It make migration difficult)
