### ISSUE TITLE
Contributing Guide

### ISSUE THREAD

**Issue by azu** [textlint/textlint#110]
We should add `CONTRIBUTING.md`.

Ref:

- [Contributing Guidelines](https://github.com/blog/1184-contributing-guidelines "Contributing Guidelines")
- http://eslint.org/docs/developer-guide/contributing/working-on-issues

**Comment by azu** [comment]
- [ ] Add link from Getting Started

**Comment by takahashim** [comment]
@azu Does this project have coding standard?
I'm not sure about eslint so much, but if this project has `.eslintrc` or something, can we use it to check against convention?

**Comment by azu** [comment]
@takahashim We have [.jscsrc](https://github.com/textlint/textlint/blob/master/.jscsrc ".jscsrc") file.
[JSCS](https://github.com/jscs-dev/node-jscs "JSCS")(JavaScript Code Style checker) check codeing style.

You can run JSCS via

```
npm run lint:js
# or
npm test
# automatically fix issue
$(npm bin)/jscs -x src
```

**Comment by takahashim** [comment]
@azu Thanks!  I didn't know it.

(Note: I don't know JavaScript well, especially ES5 and ES6)

What kind of conventions I want to know are, for example:

* Which should I use for quotation of string, such as `require("foo")` or `require('foo')`  (I think both are used, and `"validateQuoteMarks"` is null in `.jscsrc`)
* Which (and when) should I use `var` or `let` (I think both are used)
* How to write comments; which (and when) should I use `//` and `/* ... */`

Can JSCS check these things?   If not, it's very helpful for me to refer to such things in contributing guide.

**Comment by azu** [comment]
> Which should I use for quotation of string

prefer `"`(double quote)

> "validateQuoteMarks" is null in .jscsrc

Yes, it's temporary disabled...

> Which (and when) should I use var or let

`const` > `let` >>> `var`

> How to write comments

I'v used both style. I think that is no problem.

> Can JSCS check these things? 

Probably, ESLint can check these things.
We consider moving to ESLint :thought_balloon: 

> If not, it's very helpful for me to refer to such things in contributing guide.

Ya. I will take it after implementing fixer #131

**Comment by azu** [comment]
I'v create pull request to #139

**Comment by azu** [comment]
We have added [Contributing Guide](https://github.com/textlint/textlint/blob/master/CONTRIBUTING.md "Contributing Guide")!
