### ISSUE TITLE
bug: Different output from --stdin

### ISSUE THREAD

**Issue by joeybaker** [textlint/textlint#117]
I'm getting different output when I pass a file via stdin then when I pass a file directly:

```
>> ./node_modules/.bin/textlint --format compact readme.md        
readme.md: line 4, col 1, Error - found TODO: 'TODO: and such' (no-todo)
readme.md: line 39, col 22, Error - warning(passive) "be executed" may be passive voice (rousseau)
readme.md: line 39, col 118, Error - warning(readibility) sentence is very hard to read (rousseau)
readme.md: line 41, col 1, Error - suggestion(readibility) sentence is hard to read (rousseau)
readme.md: line 44, col 102, Error - warning(passive) "be updated" may be passive voice (rousseau)
readme.md: line 44, col 192, Error - suggestion(simplicity) "modify" has a simpler alternative
Suggestions:
=> change (rousseau)
readme.md: line 48, col 254, Error - warning(weasel) "few" is a weasel word (rousseau)
readme.md: line 55, col 1, Error - suggestion(simplicity) "In addition" has a simpler alternative
Suggestions:
=> also, besides, too (rousseau)
readme.md: line 55, col 169, Error - warning(passive) "be used" may be passive voice (rousseau)
readme.md: line 76, col 75, Error - suggestion(simplicity) "very" has a simpler alternative
Suggestions:
=> omit (rousseau)
readme.md: line 76, col 75, Error - warning(adverbs) adverbs can weaken meaning (rousseau)
readme.md: line 76, col 75, Error - warning(weasel) "very" is a weasel word (rousseau)

12 problems
```

```
>> cat readme.md | ./node_modules/.bin/textlint --format compact --stdin
<text>: line 4, col 1, Error - found TODO: 'TODO: and such' (no-todo)
<text>: line 29, col 1, Error - don't repeat "```" in 2 phrases (no-start-duplicated-conjunction)

2 problems

```

1. the format is different
2. the number of problems reported is different.

I'm not sure if/when I'll have type to try to tackle this myself, so let me know if there's additional debugging info I can provide.

**Comment by azu** [comment]
@joeybaker Thanks for report.

>  ./node_modules/.bin/textlint --format compact readme.md 

`textlint` will know the format of `readme.md` is markdown format, but 

> cat readme.md | ./node_modules/.bin/textlint --format compact --stdin

`textlint` will not know the format of `readme.md`.
So, `textlint --stdin` treat the content as plain text(`.txt`) by default.

It is expected behvior.

We will add `--stdin-filename` option to specify a filename to process STDIN as.
ESLint which is similar product has `--stdin-filename`.

- http://eslint.org/docs/user-guide/command-line-interface#stdin-filename

What do you think?

**Comment by azu** [comment]
#118 merged and [5.3.0](https://github.com/textlint/textlint/releases/tag/5.3.0 "5.3.0") released! 

@joeybaker please try to use `--stdin --stdin-filename <file name>`:

> cat readme.md | ./node_modules/.bin/textlint --format compact --stdin --stdin-filename readme.md

**Comment by joeybaker** [comment]
Awesome! Thanks @azu!

**Comment by joeybaker** [comment]
@azu any chance I could bother you to publish 5.3 to npm?

**Comment by azu** [comment]
oh, sorry. I publish textlint@5.3.0 now!

**Comment by joeybaker** [comment]
Thanks!
