### ISSUE TITLE
enhancement: textlintrc validation or type hint

### ISSUE THREAD

**Issue by misogihagi** [textlint/textlint#1355]
**What version of textlint are you using?**

**What file type (Markdown, plain text, etc.) are you using?**

**What did you do? Please include the actual source code causing the issue.**

**What did you expect to happen?**

**What actually happened? Please include the actual, raw output from textlint.**

Setting textrc as follows does not work.

```
{
  "rules": {
    "preset-ja-technical-writing": {
      "en-no-mixed-period": {
        "allowPeriodMarks": ""
      }
    }
  

```

Because ``allowPeriodMarks`` expects an array of strings.
So I thought a validation function might be a good idea.

Custom rules have versatility. But implementation is difficult.
Any ideas?

**Comment by azu** [comment]
To do this, the rule side must define an optional schema.
ESLint did it.

- [Custom Rules - ESLint - Pluggable JavaScript Linter](https://eslint.org/docs/latest/extend/custom-rules#options-schemas)

Related 

- #700

**Comment by misogihagi** [comment]
I understand there is a schema options project underway.
So, I close this issue.
