### ISSUE TITLE
`linter-formatter`: `is-file` is missing as a dependency

### ISSUE THREAD

**Issue by a01sa01to** [textlint/textlint#1361]
**What version of textlint are you using?**

14.0.2 (latest)

**What file type (Markdown, plain text, etc.) are you using?**
**What did you do? Please include the actual source code causing the issue.**
**What did you expect to happen?**

I tried to use `textlint` as a node module like this, with `yarn@4.1.0` (latest, PnP).

```js
import { createLinter } from "textlint";
import { TextlintKernelDescriptor } from "@textlint/kernel";

const descriptor = new TextlintKernelDescriptor({
  rules: [],
  filterRules: [],
  plugins: [],
});

const linter = createLinter({ descriptor });
```

This is almost identical to the code presented in the official documentation, and is expected to work without error.
(https://textlint.github.io/docs/use-as-modules.html#apis)

**What actually happened? Please include the actual, raw output from textlint.**

I got error that `@textlint/linter-formatter` doesn't declare`is-file` in its dependencies.

```
/workspaces/workspace/.pnp.cjs:7476
      Error.captureStackTrace(firstError);
            ^

Error: @textlint/linter-formatter tried to access is-file, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: is-file
Required by: @textlint/linter-formatter@npm:14.0.2 (via /root/.yarn/berry/cache/@textlint-linter-formatter-npm-14.0.2-5cbd085388-10c0.zip/node_modules/@textlint/linter-formatter/lib/src/)
```

Actually, it appears to use `is-file`, which isn't included as a dependency.

https://github.com/textlint/textlint/blob/ffd9a7d60c7e0576bccfff7a9e8a1592ecfcdea5/packages/%40textlint/linter-formatter/src/index.ts#L12
https://github.com/textlint/textlint/blob/ffd9a7d60c7e0576bccfff7a9e8a1592ecfcdea5/packages/%40textlint/linter-formatter/package.json#L34-L49

I think just adding it as a dependency can fix the error.

Reproduction: https://codesandbox.io/p/devbox/z54gpl?migrateFrom=hnfsk9
Please run `yarn start`.

Finally, thank you a lot for such a great tool!

**Comment by azu** [comment]
Thank you for report. 
I think it's better to implement the following function instead of adding dependency.
```js
const isFile = (filePath: string) => {
  try {
    return fs.statSync(path).isFile();
  } catch (e) {
    return false;
  }
}
```

**Comment by a01sa01to** [comment]
Thanks for the quick fix!

**Comment by azu** [comment]
Fixed in https://github.com/textlint/textlint/releases/tag/v14.0.3
