### ISSUE TITLE
severity type missmatch

### ISSUE THREAD

**Issue by paihu** [textlint/textlint#1367]
**What version of textlint are you using?**

14.0.3
**What file type (Markdown, plain text, etc.) are you using?**
html
**What did you do? Please include the actual source code causing the issue.**
textlintKernel's  lintText option type missmatch

following code's Type is valid but runtime error
`Error: Please set following value to severity:
"rule-key": {
    "severity": "<warning|error>"
}`
```
const kernel = new TextlintKernel();
kernel.lintText("text", {
  rules: [
    {
      ruleId: "sample",
      rule: ruleObject,
      options: { severity: 2 },
    },
  ],
  ext: ".html",
  plugins: [{ pluginId: "html", plugin: htmlPlugin }],
});

```

following code's Type is invalid but no error
```
const kernel = new TextlintKernel();
kernel.lintText("text", {
  rules: [
    {
      ruleId: "sample",
      rule: ruleObject,
      options: { severity: "error" },
    },
  ],
  ext: ".html",
  plugins: [{ pluginId: "html", plugin: htmlPlugin }],
});

```

rules require [SeverityLevel](https://github.com/textlint/textlint/blob/master/packages/%40textlint/types/src/Rule/TextlintRuleSeverityLevel.ts#L9) 0|1|2

but [getSeverity](https://github.com/textlint/textlint/blob/master/packages/%40textlint/kernel/src/task/linter-task.ts#L58) require ["none"|"info"|"error"|"warn"](https://github.com/textlint/textlint/blob/master/packages/%40textlint/kernel/src/context/TextlintRuleSeverityLevelKeys.ts#L9-L12)

**What did you expect to happen?**

**What actually happened? Please include the actual, raw output from textlint.**

```
Error: Please set following value to severity:
"rule-key": {
    "severity": "<warning|error>"
}
```

**Comment by azu** [comment]
I think the type information is wrong because it should be the same as the option of `.textlinrc.json`.

Next, we should fix the types so that we can compile the code.

```ts
const kernel = new TextlintKernel();
kernel.lintText("text", {
  rules: [
    {
      ruleId: "sample",
      rule: ruleObject,
      options: { severity: "error" },
    },
  ],
  ext: ".html",
  plugins: [{ pluginId: "html", plugin: htmlPlugin }],
});
```

**Comment by azu** [comment]
Fixed in https://github.com/textlint/textlint/releases/tag/v14.0.4

Thanks!
