### ISSUE TITLE
suggest: replace `traverse` by `neotraverse` in `markdown-to-ast`

### ISSUE THREAD

**Issue by Jayllyz** [textlint/textlint#1400]
https://npmgraph.js.org/?q=traverse vs https://npmgraph.js.org/?q=neotraverse

`neotraverse` repo : https://github.com/PuruVJ/neotraverse

<img width="560" alt="image" src="https://github.com/user-attachments/assets/44498da2-c1d1-41af-a689-e77294c21a06">

*https://github.com/TheDevMinerTV/package-size-calculator*

*https://github.com/es-tooling/ecosystem-cleanup*

(I can open a PR if needed)

**Comment by azu** [comment]
Looks good. Welcome PR
