### ISSUE TITLE
Font (Lato) missing from documentation website

### ISSUE THREAD

**Issue by joaopalmeiro** [textlint/textlint#1403]
Hi! 👋 

When accessing the documentation website, I noticed an unexpected font for the main button and navigation menu. Since I don't have Lato installed on my device (and I didn't find a `@font-face` to specify a custom font for the documentation website), the font shown is Times (the default `serif` font for macOS):

<img width="1582" alt="Screenshot 2024-08-07 at 11 31 51" src="https://github.com/user-attachments/assets/9d685033-53a6-4133-8edb-aa6893e5f316">

If you consider this an issue, a possible solution is to make the font available via [Fontsource](https://fontsource.org/fonts/lato), for example. 

If taking advantage of the fact that Lato is installed on the user's device is something relevant, it is possible to adapt the Fontsource stylesheet (or the equivalent one from another provider) to include the [`local()` function](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face#description). Thus, if Lato is installed on the user's device, it will be used directly. It's a trade-off between readiness and simplicity vs. optimization, I would say.

Let me know your thoughts and if I can open a PR to help. Thanks!

**Comment by azu** [comment]
Good catch!
I think it is appropriate to remove Lato.

https://github.com/textlint/textlint/blob/b441ff8718e62dd0445cb8ac346e195e78e01435/website/static/css/custom.css#L29
https://github.com/textlint/textlint/blob/b441ff8718e62dd0445cb8ac346e195e78e01435/website/static/css/index.css#L87

Original Design file is here
https://www.figma.com/design/KNfHTykmdSqNDdGDN2pUVl/textlint-website?node-id=0-23&t=kn8WKYWc01BRrQnc-0
https://github.com/textlint/media/issues/4

**Comment by joaopalmeiro** [comment]
Thanks for the feedback!

So, the idea is to remove Lato and the `font-family` for these elements to be the default one?

<img width="1582" alt="image" src="https://github.com/user-attachments/assets/e44260bd-e780-4a76-957a-c6770f8c0874">

If yes, can I open a PR?
