### ISSUE TITLE
Some internal modules (try-resolve@1.0.1) are 'deprecated'.

### ISSUE THREAD

**Issue by stein2nd** [textlint/textlint#1406]
**What version of textlint are you using?**
v14.0.5

**What did you expect to happen?**
npm warn deprecated try-resolve@1.0.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.

![image](https://github.com/user-attachments/assets/57ab06f9-c823-4eb6-b7f7-60bedc952f63)

## System:
 - OS: macOS 14.6.1
 - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 2.13 GB / 32.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 22.6.0 - ~/.nodebrew/node/v22.6.0/bin/node
 - Yarn: 1.22.22 - /usr/local/bin/yarn
 - npm: 10.8.2 - ~/.nodebrew/node/v22.6.0/bin/npm

**Comment by azu** [comment]
https://github.com/secretlint/secretlint/blob/410818b45c8dfad5bf53e0238c027f66126ea65e/packages/%40secretlint/config-loader/src/SecretLintModuleResolver.ts#L10-L17

Probably, we can replace it with plain function.

**Comment by lumirlumir** [comment]
This is the original code for the try-resolve package:

https://www.npmjs.com/package/try-resolve?activeTab=code

```javascript
var Module = require("module");

var resolve = module.exports = function (loc, _require) {
  try {
    return (_require || require).resolve(loc);
  } catch (err) {
    return null;
  }
};

var relativeMod;

resolve.relative = function (loc) {
  // we're in the browser, probably
  if (typeof Module === "object") return null;

  if (!relativeMod) {
    relativeMod = new Module;
    relativeMod.paths = Module._nodeModulePaths(process.cwd());
  }

  try {
    return Module._resolveFilename(loc, relativeMod);
  } catch (err) {
    return null;
  }
};
```

I think I can improve this. Would it be alright if I go ahead with the fix? @azu
