### ISSUE TITLE
 Compliances tests for TxtNode

### ISSUE THREAD

**Issue by azu** [textlint/textlint#141]
`TxtNode` is defined as docs/

- https://github.com/textlint/textlint/blob/master/docs/txtnode.md

We'll create `textlint-txt-node-tester` module.
It is similar to Promise A/+ tester and adapter approach.

- [promises-aplus/promises-tests: Compliances tests for Promises/A+](https://github.com/promises-aplus/promises-tests)
- [zenparsing/es-observable: Observables for ECMAScript](https://github.com/zenparsing/es-observable)

The motivation of the module is that plugin creator easy to create new plugin.

Any thought?

Related #122 

### Next Step

- Rename [TxtSyntax](https://github.com/textlint/textlint/blob/master/docs/txtnode.d.ts "TxtSyntax") to `TxtAST`
- Define `value` to `TxtNode`
     - Split `TxtNode` to `ParentNode` and `InlineNode`
- Add note about https://github.com/wooorm/unist

**Comment by azu** [comment]
https://github.com/textlint/textlint/blob/master/docs/txtnode.md#txtnode-interface-1 don't define `value` property.
I think `value` is depended on the Syntax, but it is useful for some utility.

- https://github.com/azu/textlint-util-to-string

We want to define **What is value?**

By contrast, 

Q. What is `raw`?
A. `raw` is the vaue of Node's `range`.

**Comment by azu** [comment]
My answer to "What is value?"

A. Inline Node should have `value`. It is plain vaue removed decoration.

**Comment by azu** [comment]
I thinks that DOM Node's specification have the answer to "What is value?".

**Comment by azu** [comment]
Idealistically, it is good that will be compatible for https://github.com/wooorm/unist

**Comment by azu** [comment]
I notice that current TxtNode is compatible for unist?

Difference:

- `TxtNode` is not defiend [Text](https://github.com/wooorm/unist#text "Text"), but we will define this in the issue.
- `location` on Unist is `loc` in TxtNode.
- [Position](https://github.com/wooorm/unist#position "Position")'s column is 1-indexed, but TxtNode's positon is 0-indexed.

**Comment by wooorm** [comment]
As an aside, why not use Unist directly? A benefit would be that you could use all the already existing  utilities.

**Comment by azu** [comment]
> As an aside, why not use Unist directly?

I think that backword-compatibility for textlint's rule is important.

**Comment by wooorm** [comment]
Hmm, okay. I’d still suggest to do so in a major release though :)

**Comment by azu** [comment]
I'v created test module https://github.com/textlint/textlint-ast-test and update document #170 
This update only reflect current status. It won't contain any changes for parser.

**Comment by wooorm** [comment]
:+1:

**Comment by azu** [comment]
closed by #170
