### ISSUE TITLE
Question: Default severity for non-RuleError report is always "info"?

### ISSUE THREAD

**Issue by io-monad** [textlint/textlint#144]
Hi,

I'm creating Chrome Extension for textlint and noticed that some rules report `info` severity messages. For example, textlint-rule-preset-JTF-style reports `1.1.2` using `info` severity, although there is no severity specified in [the source](https://github.com/azu/textlint-rule-preset-JTF-style/blob/master/src/1.1.2.js#L32)

I've read [the document about fixer](https://github.com/textlint/textlint/blob/master/docs/rule-fixable.md) and found that the example code is using `context.report(node, { column: ... })` style instead of `context.report(node, new RuleError({ ... }))` style.

From source code, I understand the severity for that type of call is `info` by default, and not respecting `severity` value from `ruleConfig`.
https://github.com/textlint/textlint/blob/master/src/rule/rule-context.js#L59

OTOH, for a call with RuleError, it uses `error` by default and respecting `ruleConfig`.
https://github.com/textlint/textlint/blob/master/src/rule/rule-context.js#L18

Is that intended or not intended?

IMHO the default severity should always be `error` since textlint is a linter tool, not a suggestion tool.

**Comment by azu** [comment]
Ah, Good question!

> I've read the document about fixer and found that the example code is using context.report(node, { column: ... }) style instead of context.report(node, new RuleError({ ... })) style.

Answser: [rule-fixable.md](https://github.com/textlint/textlint/blob/master/docs/rule-fixable.md "rule-fixable.md") is wrong.
We should use `context.report(node, new RuleError({ ... }))` style.
`context.report(node, { index: ... })` style was un-document way I think.
I have introduced object literal style for [textstat](https://github.com/azu/textstat "textstat"). 
`textlint` user need not use the object literal style.

We'll fix the document and jtf-style :bow: 

> IMHO the default severity should always be error since textlint is a linter tool, not a suggestion tool.

Yes :+1: 
A rule could not define `severity` level. `severity` level should be defined by user.

**Comment by io-monad** [comment]
All right, I understand. Thank you for quick response!

Never mind about documentation. Software always grows up with users! :wink:

**Comment by azu** [comment]
I fix the document https://github.com/textlint/textlint/commit/641d9bdbd9283c184a91b674835f3005d5365613

Thanks again!
