### ISSUE TITLE
Error/warning format examples?

### ISSUE THREAD

**Issue by kozross** [textlint/textlint#154]
I'm trying to write a plugin to support textlint in [Flycheck][1], but I'm not too sure what the output of textlint looks like. Is there a standard output format for all textlint plugins/checkers, and if so, where could I find an example of it?

[1]: https://github.com/flycheck/flycheck

**Comment by azu** [comment]
:memo: Document here https://github.com/textlint/textlint/blob/master/docs/formatter.md

texlint formatter is compatible for [eslint](http://eslint.org/docs/developer-guide/working-with-custom-formatters "eslint").
