### ISSUE TITLE
astexplorer like tool

### ISSUE THREAD

**Issue by azu** [textlint/textlint#176]
[AST explorer](https://astexplorer.net/ "AST explorer") is useful for JavaScript AST.

I'v see [Add new transformer for creation of ESLint rules by Daniel15 · Pull Request #104 · fkling/astexplorer](https://github.com/fkling/astexplorer/pull/104 "Add new transformer for creation of ESLint rules by Daniel15 · Pull Request #104 · fkling/astexplorer") and I want to textlint version.

It is a possible to create, I think.

- How to add a new parser
- How to add a new transformer

in [README.md](https://github.com/fkling/astexplorer#how-to-add-a-new-parser "README.md")

**Comment by hzoo** [comment]
Definitely possible since theres ones for css/html/etc

**Comment by azu** [comment]
WIP https://github.com/azu/astexplorer/pull/1 

- textlint's markdown/txt parser work fine.
- textlint's markdown/txt transform don't work.

![ast explorer 2016-03-27 12-59-46](https://cloud.githubusercontent.com/assets/19714/14063786/cba32e98-f41b-11e5-9ea2-b1d8172e541f.png)

**Comment by azu** [comment]
transformers just work.
![ast explorer 2016-03-27 13-36-32](https://cloud.githubusercontent.com/assets/19714/14063851/f874f49c-f420-11e5-8ca8-d4ea89bb54d0.png)

**Comment by azu** [comment]
land https://textlint.github.io/astexplorer/
