### ISSUE TITLE
Some plugins don't work

### ISSUE THREAD

**Issue by jimo1001** [textlint/textlint#180]
I'm using textlint v6.0.3. This version seems to not work plugins(More preceisely, non-embedded `Processor`).
I confirmed that it has occurred with `textlint-plugin-html` and my plugins in process of creation.

**Comment by azu** [comment]
Thanks for report.
I'll see lator.

**Comment by azu** [comment]
I confirm bug about Processor plugin.

When load a plugin, then add available extensions like `.html"` to core.
textlint v6.x has the issue of available extensions.

I try to fix this issue.

**Comment by azu** [comment]
I've fixed this issue on #181 and I'll release 6.0.4 :soon:

**Comment by azu** [comment]
@jimo1001 Realse [6.0.4](https://github.com/textlint/textlint/releases/tag/6.0.4 "6.0.4").

**Comment by jimo1001** [comment]
Thank you for fixing it so quickly!
All processor plugins worked fine :smile:

**Comment by azu** [comment]
Thank you for checking :)
