### ISSUE TITLE
.textlintrc support `rulesdir`

### ISSUE THREAD

**Issue by azu** [textlint/textlint#190]
`textlint` already support `--rulesdir` command line option.
May `.textlintrc` support `rulesdir` or `rulesDirectory`?

We are careful to introduce new feature to `.textlintrc`.
Because, complex configuration is bad.

But, supporting `rulesdir` is reasonable feature, I think.
## Use case

A project use textlint and some textlint rules.

``` js
{
  "rules": {
    "no-todo": true,
    "very-nice-rule": true,
  }
}
```

We add _specific_\* rule to the project.

e.g.) Not use **I think**

We can create a rule like `textlint-rule-no-i-think`, but may resistant to publish the rule to npm.

If `rulesdir` option, adding the specific rule file to the project.

``` js
{
  "rulesdir": ["./rules"],
  "rules": {
    "no-todo": true,
    "very-nice-rule": true,
  }
}
```

**Comment by azu** [comment]
Related issue: https://github.com/eslint/eslint/issues/2715

**Comment by matthew-piziak** [comment]
Agreed. This blocks my being able to use this on NixOS without a global NPM installation. 

For reference, I run `textilnt` like this:
```
textlint --config ~/.textlintrc --rulesdir /nix/store/qrd01jqgkxh681h5w98a4hz7jxi0kzhm-node-textlint-rule-write-good-1.6.2/lib/node_modules/textlint-rule-write-good/lib file.txt
```

**Comment by azu** [comment]
Now, npm,yarn,pnpm support workspaces as native.
Today, `--rulesdir` is not good idea.

We will not support `rulesdir` by config.
