### ISSUE TITLE
Proposal: textlint --try feature

### ISSUE THREAD

**Issue by azu** [textlint/textlint#201]
We want to try an rule quickly.

Rule owner write usage like following:

``````
## Usage

Via `.textlintrc`(Recommended)


```json
{
    "rules": {
        "rousseau": {
            "showLevels": ["suggestion", "warning", "error"]
        }
    }
}
```

Via CLI

```
textlint --rule rousseau README.md
```
``````

We want to add "Trying the rule" to the Usage:

Image

```
$ textlint-try rousseau
# Launch REPL-like trying mode
# Or Open browser and try the rule
```

The idea is inspired by [CocoaPods/cocoapods-try: CocoaPods plugin which allows to quickly try the demo project of a Pod.](https://github.com/CocoaPods/cocoapods-try).

**Comment by joshi-mehul** [comment]
@azu looks very good idea

**Comment by azu** [comment]
npx(which is built-in npm 5) help this.

- [Introducing npx: an npm package runner – Kat Marchán – Medium](https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b "Introducing npx: an npm package runner – Kat Marchán – Medium")

**Comment by azu** [comment]
Oneliner for textlint rules.

```shell
$ npx -p textlint -p textlint-rule-no-todo textlint --rule no-todo README.md
```

**Comment by azu** [comment]
npx resolve this issue
