### ISSUE TITLE
Proposal: "ignoring rule" to be "filter rule"

### ISSUE THREAD

**Issue by azu** [textlint/textlint#212]
After long discussion #211, We decied that introduce "filter rule" and remove "ignoring rule".

## Problem of "ignoring rule"

Original issue is " `--fix` with ignoring rule does't work #211 ".

This issue is came from a bit strange configuration format.

```
{
   // mixed "rule" and "ignoring rule"
   "rules": {
       "no-todo",
       "ignore-comments"
   }
}
```

It was mixed normal rule and ignoring rule in `"rules"` filed.
They are confused.

## 🆕 "filter rule"

- Replace "ignoring rule" with "filter rule"
- Add "filters" filed support to textlint core
	- Same convention with "rules" field
- Rename "[textlint-rule-report-node-types](https://github.com/textlint/textlint-rule-report-node-types)" to "textlint-filter-rule-node-types". Is it better conventional name?
- Filter rule use `shouldIgnore(range, { ruleId })` API
  - https://github.com/textlint/textlint/blob/master/docs/rule.md
- textlint core still has actual filtering logic. - That is [message-filter.js](https://github.com/textlint/textlint/blob/master/src/shared/message-filter.js "message-filter.js")
  - [textlint-filter-plugin](https://github.com/textlint/textlint/issues/211#issuecomment-220991535) pattern is difficult.
  - We like simple.
- The order of filters doesn't affect result.
- textlint not allow (normal) rule to use `shouldIgnore`.

e.g.) The user want to use `textlint-filter-rule-node-types` and set following to  `.textlintrc` 

```json
{
   "filters": {
      "node-types": {
      	"nodeTypes": ["BlockQuote"]
      }
   },
   "rules": {}
}
```

## Any breaking changes?

Yes and No.

"ignoring rule" is experimental feature #193 
This change does't affect to textlint user.

**Comment by azu** [comment]
Todo

- [ ] Update document
- [ ] rename filter rules
- [ ] validate textlintrc

**Comment by azu** [comment]
Done [6.9.0](https://github.com/textlint/textlint/releases/tag/6.9.0 "6.9.0")

**Comment by orangain** [comment]
@azu Finally, I have used `--fix` with the filter rules, both [textlint-filter-rule-comments](https://github.com/textlint/textlint-filter-rule-comments) and [textlint-filter-rule-node-types](https://github.com/textlint/textlint-filter-rule-node-types). They worked really good 🎉  Thanks a lot!

**Comment by azu** [comment]
@orangain Thanks to confirm.
