### ISSUE TITLE
textlint rule database

### ISSUE THREAD

**Issue by azu** [textlint/textlint#253]
We want to create textlint rule search page like gulp plugin registry.

- [gulp.js plugin registry](http://gulpjs.com/plugins/ "gulp.js plugin registry")

@io-monad has created [textlint-registry](https://github.com/io-monad/textlint-registry "io-monad/textlint-registry: Unofficial registry of JSON Schema files of textlint rule configurations") that has available textlint rules and rule schema.

@1000ch has created [textlint-rule-documentation](https://github.com/1000ch/textlint-rule-documentation "textlint-rule-documentation") that finding documentation(homepage?) for each textlint rule.

also, We have a [Collection of textlint rule · textlint/textlint Wiki](https://github.com/textlint/textlint/wiki/Collection-of-textlint-rule "Collection of textlint rule · textlint/textlint Wiki").

These whitelist approach is important, but they have maintain cost.
Publish new textlint rule and update registry/wiki...

To reduce maintain cost for developer, We should create new ecosystem dependent npm.
Because, we have used npm for publishing own textlint rule.

For example, [gulpjs/plugins](https://github.com/gulpjs/plugins "gulpjs/plugins") work following rule. It use `keywords` of `package.json`

> This app is a simple client-side app that allows one to browse and search gulp plugins. It fetches data from npmsearch with the keywords gulpplugin and gulpfriendly. [npmsearch](http://npmsearch.com/) also provides rankings for plugins(so we don't have to).

I think that we start by adding keywords `textlintrule` to own textlint rule.

- rule : `textlintrule`
- preset: `textlintrule`
- filter-rule: `textlintrule`
- plugin: `textlintplugin`

This rules are similar with [eslint](http://eslint.org/docs/developer-guide/working-with-plugins#share-plugins) and gulp.

I believe that some problems are resolved by tagging keyword and using  [npmsearch](http://npmsearch.com/) API.

**Comment by 1000ch** [comment]
`1000ch/textlint-rule-documentation` is a map of rule id to document URL.
(To refer from `linter-textlint` originally.)

**Comment by azu** [comment]
Internally, textlint resolve rule id to package name by [TextLintModuleResolver](https://github.com/textlint/textlint/blob/5f9cfc78e07a13af0dd548448eda247e93e476cc/src/engine/textlint-module-resolver.js#L70-L82). But, textlint doesn't treated meta data of rule package.

**Comment by azu** [comment]
Done. Adding `telintrule` keywords
