### ISSUE TITLE
Tear down

### ISSUE THREAD

**Issue by UFOMelkor** [textlint/textlint#266]
I try to connect textlint with the [node-languagetool](https://github.com/schreiben/node-languagetool).
node-languagetool runs a service and then sends commands to this service which are executed asynchronously.
Thanks to #75 this is no problem. But the service started by node-languagetool is running until it is explicitly killed. Is there any way to execute this *after* all checks are done?

**Comment by azu** [comment]
textlint doesn't provide `after-all` hook, but you can write following:

```js
var lt = require('node-languagetool');
module.exports = (context) => {
  const {Syntax, getSource, RuleError, report} = context;
  const promiseQueue = [];
  return {
    [Syntax.Str](node) {   
      var text = getSource(node);    
      // add queue  
      promiseQueue.push(lt.check(text));
    },
    // call at the end
    // Syntax.Document <-> Syntax.Document:exit
    // https://github.com/textlint/textlint/blob/master/docs/rule.md
    [`${Syntax.Document}:exit`](node){
      // Note: textlint wait for `Promise.all` is resolved.
      return Promise.all(promiseQueue).then((...responses) => {
        responses.forEach(response => {
           // do somthing...
        });
      }).then(() => {
          // after-all
      });
    }
  }
}
```

**Comment by UFOMelkor** [comment]
That works, thank you :+1:

**Comment by azu** [comment]
We will add a documentation about this question.
https://github.com/textlint/textlint/pull/269
