### ISSUE TITLE
When --fix, should have empty applyingMessages and remainingMessages

### ISSUE THREAD

**Issue by azu** [textlint/textlint#273]
Currently, textlint --fix result has following

```js
[ { messages : []. filePath }]
```

It should be more safe by following.

```js
[ { messages : [], remainingMessages:[], applyingMessages:[], filePath }]
```

**Comment by 0x6b** [comment]
@azu, `textlint-kernel-interface` seems to have `applyingMessages` and `remainingMessages`.What issue have to solved in this ticket?

https://github.com/textlint/textlint/blob/1378129cf3d372471498a48d3af6254730c982f0/packages/%40textlint/kernel/src/textlint-kernel-interface.ts#L207-L210

https://github.com/textlint/textlint/blob/1378129cf3d372471498a48d3af6254730c982f0/packages/%40textlint/kernel/src/fixer/source-code-fixer.ts#L112-L118

**Comment by azu** [comment]
> [ { messages : [], remainingMessages:[], applyingMessages:[], filePath }]

I have not reproduce test case. (I have seen the error when run `textlint --fix`, and I've created the issue) 
Maybe it's just my imagination.

I think that we have three approch to this issue.

1. If it was already fixed, Just close it
2. Add more test cases for `TextlintKernel#fixText`
  - Actually, the amount of test case is not much #369
  - [Integration test](https://github.com/textlint/textlint/tree/master/test/integration-test "Integration test") cover `TextlintKernel#lintText`, but it does not cover `fixText`
3. Add assertion that `applyingMessages` is not undefined with feature flag
  - [@textlint/feature-flag](https://github.com/textlint/textlint/tree/master/packages/%40textlint/feature-flag "@textlint/feature-flag") can realize it

In either case, this issue can be closed.

**Comment by 0x6b** [comment]
@azu, thank you for the clarification. We can work on this with reproducible test case in the future.

As for number of test cases, current extensive (for me) coverage made me jump in to the code base really easy. I will look into #369.
