### ISSUE TITLE
Cannot pass `npm run test:packages`

### ISSUE THREAD

**Issue by Leko** [textlint/textlint#335]
Hi there.
I try to contribute textlint, but cannot pass `npm run test:packages` or `npm test` because it failed in linter(prettier) errors.

```
/Users/leko/.ghq/github.com/Leko/textlint/packages/textlint-tester/src/test-util.js
  58:120  error  Replace `lines.length` with `⏎····················lines.length⏎················`  prettier/prettier

/Users/leko/.ghq/github.com/Leko/textlint/packages/textlint/src/core/rule-creator-set.js
  102:15  error  Delete `·`  prettier/prettier
```

### packages/textlint-tester/src/test-util.js
```js
                `lint result's line number is line:${resultMessageObject.line}, but total line number of the text is ${lines.length}.
```

prettier says:

```
${lines.length}
```

It should be:

```
${
	lines.length
}
```

### packages/textlint/src/core/rule-creator-set.js
```js
     *  ruleCreatorSet.forEach(({ruleId, rule, ruleConfig}) => {
     *      // 
     *  });
```

Contains trailing space

## Solution
I think that should run `npm run prettier`.
`npm test` and `npm run test:packages` works fine after run `npm run prettier` script.

## My environments

```
$ node -v
v6.1.0

$ npm -v
3.8.6
```

How do you think ? @azu

**Comment by azu** [comment]
Fmm, `npm run test:packages` is not failed on my enviroments.

> I think that should run npm run prettier.

Ok, Welcome to Pull Request.

Please wait a bit until merge #332

**Comment by azu** [comment]
Ah, I and CI use `yarn`.
Root directory has `yarn.lock`. 
Maybe, `npm install`  install different version of prettier.
We should use `~` to `prettier` dependencies.

**Comment by azu** [comment]
This "install" document is missing in [CONTRIBUTING.md](https://github.com/textlint/textlint/blob/master/.github/CONTRIBUTING.md "CONTRIBUTING.md").

**Comment by azu** [comment]
#332 is merged, Now.

**Comment by Leko** [comment]
> Ah, I and CI use yarn.
> Root directory has yarn.lock.
> Maybe, npm install install different version of prettier.

I got it.
I will replace npm with yarn.

**Comment by Leko** [comment]
It works fine use yarn instead of npm.
Thanks !

> This "install" document is missing in CONTRIBUTING.md.

I create a new issue #339
