### ISSUE TITLE
textlint@10.0.0

### ISSUE THREAD

**Issue by azu** [textlint/textlint#346]
### @textlint/ast-node-types: `TxtNode` type interface

`@textlint/ast-node-types` get `TxtNode` type interface #358 
It is useful for TypeScript user.

For more details. see <https://github.com/textlint/textlint/blob/master/docs/txtnode.md>

### textlint:  Use with TypeScript #248 

[@textlint/kernel](https://github.com/textlint/textlint/tree/master/packages/%40textlint/kernel "@textlint/kernel") and [textlint](https://github.com/textlint/textlint/tree/master/packages/textlint "textlint")  export type interfaces.

```ts
// Types
import {
    TextlintResult,
    TextlintFixResult,
    TextlintFixCommand,
    TextlintMessage,
    // Kernel rule/filter/plugin format
    TextlintKernelRule,
    TextlintKernelFilterRule,
    TextlintKernelPlugin,
    // Notes: Following interface will be separated module in the future.
    // textlint rule interface
    TextlintRuleCreator,
    TextlintRuleOptions,
    // textlint filter rule interface
    TextlintFilterRuleCreator,
    TextlintFilterRuleOptions,
    // textlint plugin interface
    TextlintPluginCreator,
    TextlintPluginOptions,
    TextlintPluginProcessor,
    TextlintPluginProcessorConstructor
} from "@textlint/kernel";
```

If you want to improve TypeScript integration, please file issue or track following issue.

- [Convert tests to TypeScript #369](https://github.com/textlint/textlint/issues/369 "Convert tests to TypeScript #369")

##  textlint-tester: support `inputPath` option #394 

textlint-tester support `inputPath` options.
It can test path-based rules.

## 🔥 Breaking Change

A breaking change, but this changes not affect to textlint tool user.
This changes affect to user that user textlint as node modules.

#### Before

Export as common js module.

```js
module.exports = {
  textlint,
  TextLintEngine,
}
```

### After

Export as named module.

```js
export { 
  textlint,
  TextLintEngine
}
```

You can import it as es named import.

```js
import { textlint } from "textlint"
```

or 

You can import it as common js module

```js
const textlint = require("textlint").textlint
```

### Stop to export unused name #344 

We have removed following from textlint.

- `TextLintNodeType`
- `TextLintMessageSeverityLevel`
- `TextLintMessageType`
  - Use `@textlint/ast-node-types` insteadof it

### Improve [Contributing Guide](https://github.com/textlint/textlint/blob/master/.github/CONTRIBUTING.md "Contributing Guide").

Issues/PR: #380 #379 #355 #352 #353 #341 #387 by @Leko and @0x6b

We have improved [Contributing Guide](https://github.com/textlint/textlint/blob/master/.github/CONTRIBUTING.md "Contributing Guide").
This [Contributing Guide](https://github.com/textlint/textlint/blob/master/.github/CONTRIBUTING.md "Contributing Guide") help you to contribute to textlint.

If you want to contribute to texltlint, let's see issues with the [`good first issue`](https://github.com/textlint/textlint/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) label.

### Monorepo #270 

Import following modules into this monorepo.

- textlint-formatter #359
- textlint-ast-test #357
- txt-ast-traverse #356 
- textlint-fixer-formatter #347 

Thanks to @Leko 

## 🎉 New Contributors

- @Leko – Refactor modules, fixes bug, and improve stability of textlint
- @0x6b - improve [Contributing Guide](https://github.com/textlint/textlint/blob/master/.github/CONTRIBUTING.md "Contributing Guide")

**Comment by azu** [comment]
I will release 10.0.0 after checking type interface of textlint and @textlint/kernel.

**Comment by Leko** [comment]
:tada:

**Comment by azu** [comment]
I've published pre-release for 10.0.0

Please try it 

```
npm install textlint@next
# or
npm install textlint@10.0.0-next.0
```

### 📝 Release operation notes

```
✈ ./node_modules/.bin/lerna publish --conventional-commits --cd-version premajor --npm-tag=next --preid=next
lerna info version 2.5.1
lerna info versioning independent
lerna info ignore [ 'integration-test', '**/yarn.lock' ]
lerna info Checking for updated packages...
lerna info Comparing with @textlint/kernel@1.0.3.
lerna info Checking for prereleased packages...

Changes:
 - gulp-textlint: 4.0.3 => 5.0.0-next.0
 - markdown-to-ast: 5.0.0 => 6.0.0-next.0
 - textlint-ast-test: 1.1.4 => 2.0.0-next.0
 - textlint-fixer-formatter: 1.0.0 => 2.0.0-next.0
 - textlint-formatter: 1.8.0 => 2.0.0-next.0
 - textlint-plugin-markdown: 3.0.3 => 4.0.0-next.0
 - textlint-plugin-text: 2.0.3 => 3.0.0-next.0
 - textlint-tester: 3.0.3 => 4.0.0-next.0
 - textlint: 9.1.1 => 10.0.0-next.0
 - txt-ast-traverse: 1.2.1 => 2.0.0-next.0
 - txt-to-ast: 2.0.0 => 3.0.0-next.0
 - textlint-example-cli: 1.0.0 => 2.0.0-next.0 (private)
 - textlint-example-config-file: 1.0.0 => 2.0.0-next.0 (private)
 - textlint-example-filter: 1.0.0 => 2.0.0-next.0 (private)
 - textlint-example-fix-dry-run: 1.0.0 => 2.0.0-next.0 (private)
 - textlint-example-fix: 1.0.0 => 2.0.0-next.0 (private)
 - textlint-example-html-plugin: 1.0.0 => 2.0.0-next.0 (private)
 - textlint-perf-test: 1.0.0 => 2.0.0-next.0 (private)
 - textlint-example-preset: 1.0.0 => 2.0.0-next.0 (private)
 - textlint-example-rulesdir: 1.0.0 => 2.0.0-next.0 (private)
 - textlint-example-use-as-module: 1.0.0 => 2.0.0-next.0 (private)
 - @textlint/ast-node-types: 2.0.0 => 3.0.0-next.0
 - @textlint/feature-flag: 2.0.0 => 3.0.0-next.0
 - @textlint/kernel: 1.0.3 => 2.0.0-next.0

? Are you sure you want to publish the above changes? Yes
lerna info publish Publishing packages to npm...
lerna info published textlint-formatter
lerna info published txt-ast-traverse
lerna info published textlint-ast-test
lerna info published @textlint/ast-node-types
lerna info published @textlint/feature-flag
lerna info published markdown-to-ast
lerna info published txt-to-ast
lerna info published @textlint/kernel
lerna info published textlint-plugin-text
lerna info published textlint-plugin-markdown
lerna info published textlint-fixer-formatter
lerna info published textlint
lerna info published gulp-textlint
lerna info published textlint-tester
lerna info git Pushing tags...
Successfully published:
 - gulp-textlint@5.0.0-next.0
 - markdown-to-ast@6.0.0-next.0
 - textlint-ast-test@2.0.0-next.0
 - textlint-fixer-formatter@2.0.0-next.0
 - textlint-formatter@2.0.0-next.0
 - textlint-plugin-markdown@4.0.0-next.0
 - textlint-plugin-text@3.0.0-next.0
 - textlint-tester@4.0.0-next.0
 - textlint@10.0.0-next.0
 - txt-ast-traverse@2.0.0-next.0
 - txt-to-ast@3.0.0-next.0
 - @textlint/ast-node-types@3.0.0-next.0
 - @textlint/feature-flag@3.0.0-next.0
 - @textlint/kernel@2.0.0-next.0
lerna success publish finished
```

**Comment by Leko** [comment]
@azu `textlint@10.0.0-next.0` has been installed successfully.
But I found a strange behavior.

```
$ $(npm bin)/textlint --version
v[object Object]
```

In `packages/textlint/src/cli.ts`, `pkgConf.sync("version")` returns object.
It is correct ?

```js
        if (currentOptions.version) {
            // version from package.json
            var pkgConf = require("pkg-conf");
            // console.log(pkgConf.sync("version")); // -> { '0': '1', '1': '.', '2': '0', '3': '.', '4': '0' }
            // console.log(require('../../../package.json').version) // -> 10.0.0-next.0
            logger_1.Logger.log("v" + pkgConf.sync("version"));
        }
```

**Comment by azu** [comment]
It looks wrong.
Ah, I figure out.
We should use [read-pkg-up](https://github.com/sindresorhus/read-pkg-up "read-pkg-up") instead of [pkg-conf](https://github.com/sindresorhus/pkg-conf "pkg-conf").
[pkg-conf](https://github.com/sindresorhus/pkg-conf "pkg-conf") handle "namespace" of pacakges.json. This usage is bad..

**Comment by azu** [comment]
I've filed it as issue.
https://github.com/textlint/textlint/issues/388

**Comment by Leko** [comment]
Thank you for create issue.

**Comment by azu** [comment]
I've released `textlint@10.0.0-next.1` that fixes #388 #389 

    npm install textlint@10.0.0-next.1

If everythings are OK, We will release stable 10.0.0 tomorrow.

<details>
<summary>📝 Release operation notes</summary>

```
$ ./node_modules/.bin/lerna publish --conventional-commits --cd-version prerelease --npm-tag=next --preid=next
lerna info version 2.5.1
lerna info versioning independent
lerna info ignore [ '**/yarn.lock' ]
lerna info Checking for updated packages...
lerna info Comparing with @textlint/ast-node-types@3.0.0-next.0.
lerna info Checking for prereleased packages...

Changes:
 - gulp-textlint: 5.0.0-next.0 => 5.0.0-next.1
 - textlint-fixer-formatter: 2.0.0-next.0 => 2.0.0-next.1
 - textlint-plugin-markdown: 4.0.0-next.0 => 4.0.0-next.1
 - textlint-plugin-text: 3.0.0-next.0 => 3.0.0-next.1
 - textlint-tester: 4.0.0-next.0 => 4.0.0-next.1
 - textlint: 10.0.0-next.0 => 10.0.0-next.1
 - textlint-example-cli: 2.0.0-next.0 => 2.0.0-next.1 (private)
 - textlint-example-config-file: 2.0.0-next.0 => 2.0.0-next.1 (private)
 - textlint-example-filter: 2.0.0-next.0 => 2.0.0-next.1 (private)
 - textlint-example-fix-dry-run: 2.0.0-next.0 => 2.0.0-next.1 (private)
 - textlint-example-fix: 2.0.0-next.0 => 2.0.0-next.1 (private)
 - textlint-example-html-plugin: 2.0.0-next.0 => 2.0.0-next.1 (private)
 - textlint-perf-test: 2.0.0-next.0 => 2.0.0-next.1 (private)
 - textlint-example-preset: 2.0.0-next.0 => 2.0.0-next.1 (private)
 - textlint-example-rulesdir: 2.0.0-next.0 => 2.0.0-next.1 (private)
 - textlint-example-use-as-module: 2.0.0-next.0 => 2.0.0-next.1 (private)
 - @textlint/kernel: 2.0.0-next.0 => 2.0.0-next.1
 - integration-test: 2.0.0-next.0 => 2.0.0-next.1 (private)

? Are you sure you want to publish the above changes? Yes
lerna info publish Publishing packages to npm...
lerna info published textlint-plugin-markdown
lerna info published textlint-plugin-text
lerna info published @textlint/kernel
lerna info published textlint-fixer-formatter
lerna info published textlint
lerna info published gulp-textlint
lerna info published textlint-tester
lerna info git Pushing tags...
Successfully published:
 - gulp-textlint@5.0.0-next.1
 - textlint-fixer-formatter@2.0.0-next.1
 - textlint-plugin-markdown@4.0.0-next.1
 - textlint-plugin-text@3.0.0-next.1
 - textlint-tester@4.0.0-next.1
 - textlint@10.0.0-next.1
 - @textlint/kernel@2.0.0-next.1
lerna success publish finished
```
</details>

**Comment by azu** [comment]
![image](https://user-images.githubusercontent.com/19714/34096536-019e3d64-e419-11e7-86bb-8ad82bbc18d5.png)

Publish https://github.com/textlint/textlint/releases/tag/textlint%4010.0.0 🎉

**Comment by azu** [comment]
Closing issue.
