### ISSUE TITLE
Rename "good for beginner" to "good first issue"

### ISSUE THREAD

**Issue by Leko** [textlint/textlint#351]
Hi there.

I think we should rename label `good for beginner` to `good first issue`.
Because `good first issue` is special keyword on Github.

> Apply the help wanted and good first issue labels to issues in your repository to highlight opportunities for people to contribute to your project
>
> &mdash; [Helping new contributors find your project with labels - User Documentation](https://help.github.com/articles/helping-new-contributors-find-your-project-with-labels/)

For example, babel/babel looks like (I'm not a contributor of Babel):
<img width="918" alt="screen shot 2017-11-29 at 20 42 35" src="https://user-images.githubusercontent.com/1424963/33373572-e2a1be04-d545-11e7-8854-7ec4cec3d2cb.png">

It reduce redundant document about how to contribute to `textlint`.
How do you think ?

**Comment by azu** [comment]
Yes!
Recently, I've changed the label `good for beginner` to `good first issue` in my tool.
I will apply the changes to textlint project.

**Comment by azu** [comment]
Renamed https://github.com/textlint/textlint/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22 

We need to note about "good first issue"  on [Contributing Guide](https://github.com/textlint/textlint/blob/master/.github/CONTRIBUTING.md)

**Comment by Leko** [comment]
I got it. I'll try to it tonight
