### ISSUE TITLE
Convert tests to TypeScript

### ISSUE THREAD

**Issue by azu** [textlint/textlint#369]
We have conveted source codes of [@textlint/kernel](https://github.com/textlint/textlint/tree/master/packages/%40textlint/kernel "@textlint/kernel") and [textlint](https://github.com/textlint/textlint/tree/master/packages/textlint "textlint") to TypeScript.
But, test codes is still JavaScript.

We want to convert to(or add) TypeScript test for it.

## Main purposes

- Add new TypeScript test code
  - It make the app stronge 
- Convert JavaScript test code to TypeScript code if it is possible
  - Some test is very hacky
  - It is not must

TypeScript test code help to find wrong type interface.

For example, current `textlint-engine` and `textfix-engine` is very strange implementation.
In other words, this implementaion is very hackly way.
Probably, It will be needed to refactor for passing typescript test code.

- https://github.com/textlint/textlint/blob/da23f7171912ccad3174f3028b2790e8f099e26f/packages/textlint/src/textlint-engine.ts#L61
- https://github.com/textlint/textlint/blob/da23f7171912ccad3174f3028b2790e8f099e26f/packages/textlint/src/textfix-engine.ts#L60

Adding or Converting test is that blame it 🔥 

## Priority

We want to get started with converting Public API testing.
Public API means that textlint and @textlint/kernel export modules.

- [textlint/src/index.ts](https://github.com/textlint/textlint/blob/master/packages/textlint/src/index.ts "textlint/src/index.ts")
- [@textlint/kernel/src/index.ts](https://github.com/textlint/textlint/blob/master/packages/%40textlint/kernel/src/index.ts "@textlint/kernel/src/index.ts")

Convert Public API testing:

**[textlint](https://github.com/textlint/textlint/tree/master/packages/textlint "textlint")**:

- [x] TextLintCore
- [x] TextFixEngine
- [x] TextLintEngine
- [x] textlint
- [x] cli

**[@textlint/kernel](https://github.com/textlint/textlint/tree/master/packages/%40textlint/kernel "@textlint/kernel")**:

- [x] [textlint-kernel-test.ts](https://github.com/textlint/textlint/blob/master/packages/%40textlint/kernel/test/textlint-kernel-test.ts "textlint-kernel-test.ts")
  - But more tests for various options

Related work: [Behind the Scenes: Improving the Repository Infrastructure - React Blog](https://reactjs.org/blog/2017/12/15/improving-the-repository-infrastructure.html#using-public-api-in-tests "Behind the Scenes: Improving the Repository Infrastructure - React Blog")

## How to add tests?

 [@textlint/kernel](https://github.com/textlint/textlint/tree/master/packages/%40textlint/kernel "@textlint/kernel") and [textlint](https://github.com/textlint/textlint/tree/master/packages/textlint "textlint")  has following [test architecture](https://github.com/textlint/textlint/tree/master/packages/textlint/test "test architecture").

- Each Test is separated by directory
- Each Test has fixtures directory

Colusion:

- Add test
- Run tests: `yarn run test`
- Pass tests 💚 

## How to convert tests?

Example: [refactor(textlint): Convert rule-loader-test.ts #370](https://github.com/textlint/textlint/pull/370 "refactor(textlint): Convert rule-loader-test.ts #370")

- Rename `.js` to `.ts`
- Run tests: `yarn run test`
- Pass tests 💚 

Other examples: [refactor(textlint): Convert textlint-core test to TypeScript #383](https://github.com/textlint/textlint/pull/383 "refactor(textlint): Convert textlint-core test to TypeScript #383")

For more details, see also [Contributing Guide](https://github.com/textlint/textlint/blob/master/.github/CONTRIBUTING.md "Contributing Guide").

----

❤️Love to pull request if you change **one** file!

**Comment by azu** [comment]
📝 Note: When I'm converting `cli-test.js`, I've met unexpected error.
It is strange behavior.
https://github.com/textlint/textlint/pull/392#issuecomment-352253836

**Comment by Navneet7716** [comment]
Hi is this still active, if yes I would like to pick it up

**Comment by azu** [comment]
This issue seems to have already been completed.
Thanks.
