### ISSUE TITLE
Dead link in getting-started.md

### ISSUE THREAD

**Issue by 0x6b** [textlint/textlint#375]
Hi, I found a 404 in the getting started guide.

**What version of textlint are you using?**

v9.1.1

**What file type (Markdown, plain text, etc.) are you using?**

N/A

**What did you do? Please include the actual source code causing the issue.**

Browse [Getting Started with textlint](https://github.com/textlint/textlint/blob/a7d0add0de4bc40763e5e9870ba93ed758e91be9/docs/getting-started.md) and found that following link is broken.

**What did you expect to happen?**

Navigate to contributing guideline.

**What actually happened? Please include the actual, raw output from textlint.**

Got [Page not found · GitHub](https://github.com/textlint/textlint/blob/master/CONTRIBUTING.md). The guideline seems to be moved to [.github/CONTRIBUTING.md](https://github.com/textlint/textlint/blob/master/.github/CONTRIBUTING.md) according to the commit textlint/textlint@5562922.

Please let me know if you need pull request for this issue as this is definitely  [`good first issue`](https://github.com/textlint/textlint/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22).

Regards,

**Comment by 0x6b** [comment]
Sorry I found missing line in the issue.

...found that following link is broken....

> Make textlint even better by contributing.

**Comment by azu** [comment]
@0x6b Thanks for report!
I'll fix the link in #376

> Please let me know if you need pull request for this issue as this is definitely good first issue.

Ah, Thanks!

**Comment by 0x6b** [comment]
Wow, what a speed! Thank you! Hope I will contribute to this project more.

**Comment by azu** [comment]
> Hope I will contribute to this project more.

Yes! Always welcome 👍
