### ISSUE TITLE
Missing step before running integration test at .github/CONTRIBUTING.md

### ISSUE THREAD

**Issue by 0x6b** [textlint/textlint#377]
Hi, I found missing step in the [contributing guideline](https://github.com/textlint/textlint/blob/a4688b99896aba26a064a081c34115acb943295e/.github/CONTRIBUTING.md).

**What version of textlint are you using?**

v9.1.1

**What file type (Markdown, plain text, etc.) are you using?**

N/A

**What did you do? Please include the actual source code causing the issue.**

According to the [guideline](https://github.com/textlint/textlint/blob/a4688b99896aba26a064a081c34115acb943295e/.github/CONTRIBUTING.md), I did following steps to start contributing (in some way :smile:).

1. Fork the repo at [GitHub](https://github.com).
2. Clone the repo locally: `git clone https://github.com/0x6b/textlint`
3. `cd` to local directory: `cd textlint`
4. Install dependencies: `yarn install`
5. Bootstrap packages: `yarn run bootstrap`
6. Run unit test: `yarn test` -- all passed.
7. Run example test: `yarn run test:examples` -- all passed.
8. Update sub modules following [Integration Test](https://github.com/textlint/textlint/blob/a4688b99896aba26a064a081c34115acb943295e/.github/CONTRIBUTING.md#integration-test): `git submodule update`
9. Run integration test: `yarn run test:integration` -- failed with `ENOENT`.

**What did you expect to happen?**

Integration test passed without error.

**What actually happened? Please include the actual, raw output from textlint.**

```sh
$ lerna run test --scope integration-test
lerna info version 2.5.1
lerna info versioning independent
lerna info scope integration-test
lerna ERR! test Errored while running script in 'integration-test'
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm run test
lerna ERR! fs.js:663
lerna ERR!   return binding.open(pathModule.toNamespacedPath(path),
lerna ERR!                  ^
lerna ERR!
lerna ERR! Error: ENOENT: no such file or directory, open '/Users/.../textlint/test/integration-test/JavaScript-Plugin-Architecture/.textlintrc'
```

I found no file in `test/integration-test/JavaScript-Plugin-Architecture/'` and other submodules such as `bitbook-starter-kit` and `magi-hacker` etc.

I got successful integration test after running `git submodule init` after step 8 above (or you can just use `git submodule update --init`) to populate submodules locally.

Thank you!

**Comment by azu** [comment]
We can resolve this issue by rewritting following text?

Before:
```
# Require git submodule
git submodule update
...
```

After:
```
# Require git submodule
git submodule update --init
...
```

Or, Just use `git clone --recursive` instead of `git clone` on [git clone](https://github.com/textlint/textlint/blob/a4688b99896aba26a064a081c34115acb943295e/.github/CONTRIBUTING.md "git clone").
(`git clone --recursive` is `git clone` + `git submodule init`)

**Comment by azu** [comment]
We can add both changes to CONTRIBUTING.md

- [ ] Change `git submodule update` to `git submodule update --init` on [Integration Test](https://github.com/textlint/textlint/blob/a4688b99896aba26a064a081c34115acb943295e/.github/CONTRIBUTING.md#integration-test "Integration Test")
- [ ] Change `git clone` to `git clone --recursive` on [git clone](https://github.com/textlint/textlint/blob/a4688b99896aba26a064a081c34115acb943295e/.github/CONTRIBUTING.md "git clone")

@0x6b Can you create a pull request for it?

**Comment by 0x6b** [comment]
@azu, thank you for prompt response. I didn't know `git clone --recursive` until now. It works well. I'm working on my pull request.

**Comment by 0x6b** [comment]
Please kindly review my very first pull request. Thank you!
