### ISSUE TITLE
Dead link in issue template

### ISSUE THREAD

**Issue by 0x6b** [textlint/textlint#379]
Hi, related to issue #375, I found another 404 in the [issue template](https://github.com/textlint/textlint/blob/a4688b99896aba26a064a081c34115acb943295e/.github/ISSUE_TEMPLATE.md).

**What version of textlint are you using?**

v9.1.1

**What file type (Markdown, plain text, etc.) are you using?**

N/A

**What did you do? Please include the actual source code causing the issue.**

Create a new issue. I see the template in the textarea with wrong link.

**What did you expect to happen?**

Correct link to bug-reporting guide.

**What actually happened? Please include the actual, raw output from textlint.**

```html
<!--
**Before** Bug Reporting, Please update textlint and try it.
Also see https://github.com/textlint/textlint/blob/master/CONTRIBUTING.md#bug-reporting
-->
```

The link should be [`https://github.com/textlint/textlint/blob/master/.github/CONTRIBUTING.md#bug-reporting`](https://github.com/textlint/textlint/blob/master/.github/CONTRIBUTING.md#bug-reporting).

**Comment by azu** [comment]
Opps. Thanks for report.

Can you create PR?

**Comment by 0x6b** [comment]
@azu Yes I will create PR.
