### ISSUE TITLE
textlint --version is broken at textlint@10.0.0-next.0

### ISSUE THREAD

**Issue by azu** [textlint/textlint#388]
https://github.com/textlint/textlint/issues/346#issuecomment-352193883 reported by @Leko 

We should use [read-pkg-up](https://github.com/sindresorhus/read-pkg-up "read-pkg-up") instead of [pkg-conf](https://github.com/sindresorhus/pkg-conf "pkg-conf").
Because, [pkg-conf](https://github.com/sindresorhus/pkg-conf "pkg-conf") handle "namespace" of pacakges.json.
We just want to get `version` value of closest pacakge.json.

**Comment by azu** [comment]
Context: `textlint` need to look up closest package.json.
Because. The path of `src/*/*.ts`(source code) and `lib/textlint/src/*/*.js`(compiled code) has different depth. So, textlint need to look up closest package.json.

**Comment by Leko** [comment]
I think pass `cwd` option like this

```js
            const pkgConf = require("read-pkg-up");
            const version = pkgConf.sync({ cwd: __dirname }).pkg.version;
            Logger.log(`v${version}`); // -> v10.0.0-next.0
```

**Comment by azu** [comment]
looks good to me.

**Comment by Leko** [comment]
I got it. I'll submit PR soon.
