### ISSUE TITLE
source property in TextLintMessage class

### ISSUE THREAD

**Issue by 0x6b** [textlint/textlint#400]
**What version of textlint are you using?**

v10.0.0

**What file type (Markdown, plain text, etc.) are you using?**

N/A

**What did you do? Please include the actual source code causing the issue.**

I would like to fix issue #399. Before adding new function(`getFormatterList`), I tried to convert `textlint-formatter` to TypeScript first as same as `textlint-fixer-formatter`.

**What actually happened? Please include the actual, raw output from textlint.**

I found no `property` in `TextLintMessage`. Which is expected?

- [`jslint-xml`](https://github.com/textlint/textlint/blob/5d72ce3270727e729416bfda0c4b6c72e611b18a/packages/textlint-formatter/test/formatters/jslint-xml.js) formatter [uses](https://github.com/textlint/textlint/blob/44ae6153e4035fd765656d0c3d4154fc72fc2429/packages/textlint-formatter/lib/formatters/jslint-xml.js#L28) `source` property ([test case](https://github.com/textlint/textlint/blob/41cae972db08731b797592b24dcd845c0138bec4/packages/textlint-formatter/test/formatters/jslint-xml.js#L31)), while
- [`TextLintMessage`](https://github.com/textlint/textlint/blob/44ae6153e4035fd765656d0c3d4154fc72fc2429/packages/%40textlint/kernel/src/textlint-kernel-interface.ts#L171) class does not have such property.

I think I'm missing something. Appreciate your comments. Thanks!

**Comment by azu** [comment]
This formatter is based on eslint project formatter.

https://github.com/eslint/eslint/blob/5a5c23ce3e18d6ba8e2a5ab0efb4cc21aaadf9cd/lib/formatters/jslint-xml.js#L29

The difference come from ESLint's message has `source` property, but textlint's message has not `source` property yet.

- [Documentation - ESLint - Pluggable JavaScript linter](https://eslint.org/docs/user-guide/formatters/ "Documentation - ESLint - Pluggable JavaScript linter")
- [textlint/formatter.md at 44ae6153e4035fd765656d0c3d4154fc72fc2429 · textlint/textlint](https://github.com/textlint/textlint/blob/44ae6153e4035fd765656d0c3d4154fc72fc2429/docs/formatter.md "textlint/formatter.md at 44ae6153e4035fd765656d0c3d4154fc72fc2429 · textlint/textlint")

**Comment by azu** [comment]
ESLint's `source` property has been added 2.0?

- [Update: add source property to LintResult object (fixes #7098) by vitorbal · Pull Request #7304 · eslint/eslint](https://github.com/eslint/eslint/pull/7304)
- [Proposal: add `sourceContext` property to the messages generated by the `eslint` object · Issue #7098 · eslint/eslint](https://github.com/eslint/eslint/issues/7098)

However, ESLint will remove `source` property at 4.0?

- https://github.com/eslint/eslint/issues/7098#issuecomment-251242459
- [Breaking: remove `source` property from individual eslint.verify messages · Issue #7358 · eslint/eslint](https://github.com/eslint/eslint/issues/7358)
- [Proposal: add `sourceContext` property to the messages generated by the `eslint` object · Issue #7098 · eslint/eslint](https://github.com/eslint/eslint/issues/7098)

**Comment by azu** [comment]
We can add new property to `TextLintMessage`, but it depended on formatter's needs.
If want to imrpove some formatter, we will start to discuss about it.
if this is not the case, I think that less is better.

**Comment by 0x6b** [comment]
@azu, thank you for prompt and detailed response as always. I understand that (1) the `source` property is inherited from ESLint formatter, and (2) current fallback implementation prevents the formatter from throwing any exception.

I totally agree with you – less is better. But it seems to me that without adding new property to `TextLintMessage`, `jslint-xml` formatter could not employ TypeScript's type system. For instance, while refactoring, if I changed exported function signature as `format(results: TextlintResult[])` as (a), I got `TS2339: Property 'source' does not exist on type 'TextlintMessage'` error at (b). Any thoughts?

`> git diff 6f777:./lib/formatters/jslint-xml.js ./src/formatters/jslint-xml.ts|`
```diff
diff --git a/packages/textlint-formatter/lib/formatters/jslint-xml.js b/packages/textlint-formatter/src/formatters/jslint-xml.ts
index 483172c..e166151 100644
--- a/packages/textlint-formatter/lib/formatters/jslint-xml.js
+++ b/packages/textlint-formatter/src/formatters/jslint-xml.ts
@@ -4,21 +4,23 @@
  */
 "use strict";
 
-var lodash = require("lodash");
+import {TextlintResult} from "@textlint/kernel";
+
+const lodash = require("lodash");
 
 //------------------------------------------------------------------------------
 // Public Interface
 //------------------------------------------------------------------------------
 
-module.exports = function(results) {
+export function format(results: TextlintResult[]) { // (a)
 
-    var output = "";
+    let output = "";
 
     output += "<?xml version=\"1.0\" encoding=\"utf-8\"?>";
     output += "<jslint>";
 
     results.forEach(function(result) {
-        var messages = result.messages;
+        const messages = result.messages;
 
         output += "<file name=\"" + result.filePath + "\">";
 
@@ -26,6 +28,7 @@ module.exports = function(results) {
             output += "<issue line=\"" + message.line + "\" " +
                 "char=\"" + message.column + "\" " +
                 "evidence=\"" + lodash.escape(message.source || "") + "\" " +
+                //                                    ^ (b) TS2339: Property 'source' does not exist on type 'TextlintMessage'
                 "reason=\"" + lodash.escape(message.message || "") +
                 (message.ruleId ? " (" + message.ruleId + ")" : "") + "\" />";
         });
```

**Comment by azu** [comment]
@0x6b Thanks for research!

We have three choice

1. Supress type error
   -  use `// @ts-ignore` comment or use `lodash.escape((message as any).source || "")`
2. Implement `source` property
3. Use `filePath. load the file content and parse/slice it.
   - `pretty-error` use this pattern: https://github.com/textlint/textlint/blob/c0693b79a48ba84620dc57235667f3d6219e174f/packages/textlint-formatter/lib/formatters/pretty-error.js#L80-L107
   - Probably, slice match line?

**Comment by 0x6b** [comment]
@azu, thank you for your comments. I prefer option 1 or 2 for following reason.

1. Use `@ts-ignore`: Simple. This is [not a recommended way](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html), but is [intended usage](https://blogs.msdn.microsoft.com/typescript/2017/10/31/announcing-typescript-2-6/) (migrating from JavaScript to TypeScript) and we can use this as marker for future improvement/refactoring point like TODO tag.
2. Use a type assertion to `any`: Simple.
3. Implement `source` property: Avoid duplicate information (eslint/eslint#7358)
4. Load/parse/slice file content like `pretty-error` formatter: Performance hit for large file?

Your comment is more than welcome. Thanks!

**Comment by azu** [comment]
I have dead simply idea 💡 

```diff
             output += "<issue line=\"" + message.line + "\" " +
                 "char=\"" + message.column + "\" " +
-                 "evidence=\"" + lodash.escape(message.source || "") + "\" " +
+                 // TODO: evidence is always empty string
+                 // See: https://github.com/textlint/textlint/issues/400
+                 "evidence=\"" + lodash.escape("") + "\" " +
                 "reason=\"" + lodash.escape(message.message || "") +
                 (message.ruleId ? " (" + message.ruleId + ")" : "") + "\" />";
         });
```

**Comment by 0x6b** [comment]
💯 
I will take your idea. Please close this ticket. Thank you for your help!

**Comment by 0x6b** [comment]
@azu, sorry I missed edit on your last comment. Let's implement Option `X` first.
