### ISSUE TITLE
No formatter test will be executed

### ISSUE THREAD

**Issue by 0x6b** [textlint/textlint#402]
Hi, I found issues while implementing possible fix for #400 locally.

**What version of textlint are you using?**

v10.0.0

**What file type (Markdown, plain text, etc.) are you using?**

N/A

**What did you do? Please include the actual source code causing the issue.**

Testing `textlint-formatter` by `yarn run test`

**What did you expect to happen?**

Formatters tests, including tests under [`test/formatters/`](https://github.com/textlint/textlint/tree/c0693b79a48ba84620dc57235667f3d6219e174f/packages/textlint-formatter/test/formatters) directory, will be executed.

**What actually happened? Please include the actual, raw output from textlint.**

Only [`textlint-formatter-test.js`](https://github.com/textlint/textlint/blob/c0693b79a48ba84620dc57235667f3d6219e174f/packages/textlint-formatter/test/textlint-formatter-test.js) was executed.

This seems to be due to glob mismatch in the [`package.json`](https://github.com/textlint/textlint/blob/c0693b79a48ba84620dc57235667f3d6219e174f/packages/textlint-formatter/package.json#L19). Solution could be as follows. Could you give me your thoughts?

```diff
diff --git a/packages/textlint-formatter/package.json b/packages/textlint-formatter/package.json
index 4c1114b..ac9de7d 100644
--- a/packages/textlint-formatter/package.json
+++ b/packages/textlint-formatter/package.json
@@ -16,7 +16,7 @@
     "bin/"
   ],
   "scripts": {
-    "test": "mocha test/*.js"
+    "test": "mocha test/**/*.js"
   },
   "directories": {
     "test": "test/"
```

...and you will get 14 failing tests for `stylish` and `table` formatters 😣

**Comment by azu** [comment]
Oh, we must to fix it... 🐛

**Comment by 0x6b** [comment]
Steps to reproduce:

```sh
cd textlint/packages/textlint-formatter
yarn run test # or
$(npm bin)/mocha test/*.js
```

Steps to fix:

```sh
$(npm bin)/mocha test/**/*.js # or
$(npm bin)/mocha --recursive test
```

As a first step, I can open a pull request for `package.json`.

**Comment by azu** [comment]
> $(npm bin)/mocha test/**/*.js

Prefer it.

**Comment by azu** [comment]
> As a first step, I can open a pull request for package.json.

Yes!

**Comment by azu** [comment]
This failure is caused by [chalk](https://github.com/chalk/chalk "chalk") coloring.
If I set `--no-color` option, pass the tests.

```
yarn test --no-color

  66 passing (78ms)

```

- chalk [Info](https://github.com/chalk/supports-color#info "Info")

**Comment by 0x6b** [comment]
Ah that could be a reason why running test from top directory have passed without failure.
