### ISSUE TITLE
Should fail when config file is invalid

### ISSUE THREAD

**Issue by sapegin** [textlint/textlint#406]
**What version of textlint are you using?**

v10.0.1

**What file type (Markdown, plain text, etc.) are you using?**

**What did you do? Please include the actual source code causing the issue.**

I have a syntax error in my .textlintrc.

**What did you expect to happen?**

Error message explaining that the config file cannot be loaded. Error exit code.

**What actually happened? Please include the actual, raw output from textlint.**

```
> textlint 'manuscript/**/*.md'


== Not have rules, textlint do not anything ==
=> How to set rule?
See https://github.com/textlint/textlint/blob/master/docs/configuring.md
```

Debug output:

<details>

```
$(npm bin)/textlint --debug 'manuscript/**/*.md'
  textlint:cli Running on files, stdin-filename: undefined +0ms
  textlint:module-loader config Config {
  textlint:module-loader   configFile: undefined,
  textlint:module-loader   rulesBaseDirectory: undefined,
  textlint:module-loader   rules: [],
  textlint:module-loader   disabledRules: [],
  textlint:module-loader   filterRules: [],
  textlint:module-loader   disabledFilterRules: [],
  textlint:module-loader   presets: [],
  textlint:module-loader   plugins: [],
  textlint:module-loader   pluginsConfig: {},
  textlint:module-loader   rulesConfig: {},
  textlint:module-loader   filterRulesConfig: {},
  textlint:module-loader   extensions: [],
  textlint:module-loader   rulePaths: [],
  textlint:module-loader   formatterName: undefined,
  textlint:module-loader   quiet: false,
  textlint:module-loader   color: true,
  textlint:module-loader   cache: false,
  textlint:module-loader   cacheLocation: '/Users/sapegin/Dropbox/Projects/_Repos/maintenance-book/.textlintcache' } +120ms
```

</details>

**Comment by azu** [comment]
@sapegin Thanks for report!
You are correct.

https://github.com/textlint/textlint/blob/b7978848be911fff3fafa9ee9b5ab6dd85f286a7/packages/textlint/src/cli.ts#L113

https://github.com/textlint/textlint/blob/b7978848be911fff3fafa9ee9b5ab6dd85f286a7/packages/textlint/src/cli.ts#L137

Currently, when occur the error, textlint exit with `0`(exit code).
It make bad experience.

We should change the exit code from `0` to `1`.

**Comment by sapegin** [comment]
And some error message would be nice too ;-)

**Comment by azu** [comment]
textlint use [rc-config-loader](https://github.com/azu/rc-config-loader "rc-config-loader").
Also, [rc-config-loader](https://github.com/azu/rc-config-loader "rc-config-loader") try to parse `.textlintrc` as JSON, YML, and JS.
In other words, parse error is normal path.

Probably, if you use `.textlintrc.json`(expected file extension), you can get parse error message.

**Comment by sapegin** [comment]
The PR is here! 🍕
