### ISSUE TITLE
New Collaborator @0x6b

### ISSUE THREAD

**Issue by azu** [textlint/textlint#418]
I'd love to add @0x6b to @textlint/collaborator.

Recently, @0x6b commits to following issues:

- Show available formatter in help #85 
- lint/fixer Formatter improvements #403 #413 #412 #410 #393
- [Contributing Guide](https://github.com/textlint/textlint/blob/master/.github/CONTRIBUTING.md "Contributing Guide") improvements #378 #379 #381

If @0x6b is ok, I will invite you to @textlint/collaborator !

/cc @Leko

**Comment by 0x6b** [comment]
@azu, please let me join to the repo as collaborator. I'm really glad to hear my small changes are recognized. Although I'm on my looong way to understand the codebase, it's my pleasure to contribute to this project!

**Comment by azu** [comment]
@0x6b Thanks for response!
I've invited @0x6b to @textlint/collaborator 🎉

**Comment by Leko** [comment]
@azu @0x6b I'm sorry for late reply.
It looks very solid +1.

**Comment by azu** [comment]
Welcome new textlint collaborator @0x6b 🎉
