### ISSUE TITLE
docs: multiple broken links

### ISSUE THREAD

**Issue by azu** [textlint/textlint#424]
https://github.com/textlint/textlint/blob/master/docs/formatter.md

> Pass following array of [TextLintResult](https://github.com/textlint/textlint/blob/master/typings/textlint.d.ts "TextLintResult") to reporter module.
> `TextLintMessage` and `TextLintResult` are defined in [textlint.d.ts](https://github.com/textlint/textlint/blob/master/typings/textlint.d.ts "textlint.d.ts").

Edit: add tasks (@0x6b)

- [x] [Advanced: Paragraph rule](https://github.com/textlint/textlint/blob/master/docs/rule-advanced.md)
- [x] ~~[Configuring textlint](https://github.com/textlint/textlint/blob/master/docs/configuring.md)~~ (no 404 or 301)
- [x] [Creating Rules](https://github.com/textlint/textlint/blob/master/docs/rule.md)
- [x] [Filter rule](https://github.com/textlint/textlint/blob/master/docs/filter-rule.md)
- [x] [Formatter](https://github.com/textlint/textlint/blob/master/docs/formatter.md)
- [x] [Getting Started with textlint](https://github.com/textlint/textlint/blob/master/docs/getting-started.md)
- [x] [Plugin](https://github.com/textlint/textlint/blob/master/docs/plugin.md)
- [x] [TxtAST interface](https://github.com/textlint/textlint/blob/master/docs/txtnode.md)
- [x] [Use as node modules](https://github.com/textlint/textlint/blob/master/docs/use-as-modules.md)

**Comment by azu** [comment]
We can embed type interface of TextLintMessage` and `TextLintResult` into this document.

```ts
// "range" is replaced by "text"
export class TextlintFixCommand {
    text: string;
    range: [number, number];
}

export class TextlintMessage {
    // See src/shared/type/MessageType.js
    // Message Type
    type: string;
    // Rule Id
    ruleId: string;
    message: string;
    // optional data
    data?: any;
    // FixCommand
    fix?: TextlintFixCommand;
    // location info
    // Text -> AST TxtNode(0-based columns) -> textlint -> TextlintMessage(**1-based columns**)
    line: number; // start with 1
    column: number; // start with 1
    // indexed-location
    index: number; // start with 0
    // Severity Level
    // See src/shared/type/SeverityLevel.js
    severity?: number;
}

// Linting result
export interface TextlintResult {
    filePath: string;
    messages: TextlintMessage[];
}

// Fixing result
export interface TextlintFixResult {
    filePath: string;
    // fixed content
    output: string;
    // all messages = pre-applyingMessages + remainingMessages
    // it is same with one of `TextlintResult`
    messages: TextlintMessage[];
    // applied fixable messages
    applyingMessages: TextlintMessage[];
    // original means original for applyingMessages and remainingMessages
    // pre-applyingMessages + remainingMessages
    remainingMessages: TextlintMessage[];
}
```


Type interface is here <https://github.com/textlint/textlint/blob/master/packages/@textlint/kernel/src/textlint-kernel-interface.ts>

This approach is similar with [textlint/txtnode.md at master · textlint/textlint](https://github.com/textlint/textlint/blob/master/docs/txtnode.md "textlint/txtnode.md at master · textlint/textlint")

**Comment by 0x6b** [comment]
Preliminary check with [no-dead-link](https://github.com/textlint-rule/textlint-rule-no-dead-link) rule showed multiple 404 and 301. Will update issue title and description.

**Comment by azu** [comment]
no-dead-link support that find local relative path.

> If not, try to get the path of the file being linted and use its parent folder as the base path.
> -- https://github.com/textlint-rule/textlint-rule-no-dead-link#relative-link-resolution

Probably, `baseURI` would be unnecessary.

```json
{
  "rules": {
    "no-dead-link": {
      "checkRelative": true
    }
  }
}
```

**Comment by 0x6b** [comment]
@azu, thank you! I will check the setup later.

**Comment by 0x6b** [comment]
@azu, I just started working with this issue along with #425, and found that it is very time consuming to edit/test `textlint/docs` as it will always start with full build. To keep documentation updated, build-test-release turn around time should be minimal. How about following changes?

- Add `docs/*` as new workspace (think this directory as a project, instead of just a bucket of documents)
- Add new `package.json` to `docs` and introduce its own dependencies, test, linting, etc.
- Add new test script to `textlint/package.json` e.g. `"test:docs": "lerna run test --scope docs"`

Separate workspace will enable us to improve documentation experience in the future (I'm thinking [GitBook](https://www.gitbook.com/) or [Docusaurus](https://docusaurus.io/)). Please let me know your thoughts.

Note: it will take some time for me to implement these changes as I'm new to Lerna 😟

**Comment by azu** [comment]
Making docs parts of monorepo is good idea 👍 

> I'm thinking GitBook or Docusaurus).

I want to use [Docusaurus](https://docusaurus.io/ "Docusaurus").
I've already tried to monorepo + Docusaurus in https://github.com/almin/almin
It look like good experience.

Also, It need to refactor https://github.com/textlint/textlint.github.io

**Comment by 0x6b** [comment]
Thank you @azu. I opened new issue #434. I will try to close this issue #424 first.
