### ISSUE TITLE
docs: use textlint-rule-no-dead-link for linting

### ISSUE THREAD

**Issue by azu** [textlint/textlint#425]
[textlint-rule-no-dead-link](https://github.com/textlint-rule/textlint-rule-no-dead-link "textlint-rule-no-dead-link") found dead link in document.

We want to add this rule to our [textlint/docs/.textlintrc](https://github.com/textlint/textlint/blob/master/docs/.textlintrc "textlint/docs/.textlintrc").

## Tasks

- [ ] Add `textlint-rule-no-dead-link` to [textlint/docs/.textlintrc](https://github.com/textlint/textlint/blob/master/docs/.textlintrc "textlint/docs/.textlintrc")
- [ ] Fix dead link that includes #424 

## Related Issue

This rule also can found "docs: Broken link in formatter.md #424"

**Comment by 0x6b** [comment]
Related: https://github.com/textlint-rule/textlint-rule-no-dead-link/issues/96
