### ISSUE TITLE
Remove `yarn.lock` in pacakges/*

### ISSUE THREAD

**Issue by azu** [textlint/textlint#437]
textlint use yarn workspace #340 
It means that only use `yarn.lock` in root directory.

- https://github.com/textlint/textlint/blob/master/yarn.lock

But `packages/*` has existing `yarn.lock`.
We can remove `yarn.lock` from `packages/*`

## TODO

Remove following `yarn.lock`

- [ ] [textlint/packages/gulp-textlint/yarn.lock](https://github.com/textlint/textlint/blob/a144570246d0ec89cbe370f80b5e0706e5c0647a/packages/gulp-textlint/yarn.lock "textlint/packages/gulp-textlint/yarn.lock")

**Comment by 0x6b** [comment]
Fresh clone shows only `packages/gulp-textlint` have the lock file.

```sh
$ find packages -name yarn.lock
packages/gulp-textlint/yarn.lock
```

**Comment by azu** [comment]
Ah, nice catch.

https://github.com/textlint/textlint/search?utf8=%E2%9C%93&q=+extension%3Alock&type=
