### ISSUE TITLE
Drop Node.js 4.x support

### ISSUE THREAD

**Issue by azu** [textlint/textlint#443]
![image](https://user-images.githubusercontent.com/19714/34462150-45ee47c2-ee80-11e7-84da-241ee367c3bc.png)

> [nodejs/Release: Node.js Foundation Release Working Group](https://github.com/nodejs/Release "nodejs/Release: Node.js Foundation Release Working Group")

Node.js 4.x is already Maintaince mode.
Node.js 4.x will be EOL at April 2018.

We will drop Node.js 4.x support in near future.

This issue track Node.js 4.x support.

## Plan

- [x] Update CI https://github.com/textlint/textlint/blob/53eb7bdcf0f90da8906d75d6e92a1ed236680892/.travis.yml#L4 #507 
  - Remove node v4, instead of add node v6 as minimal support
- [ ] Add `engines` to [textlint/package.json](https://github.com/textlint/textlint/blob/master/packages/textlint/package.json "textlint/package.json")?
- [ ] Update readme

This means that dropped testing in Node.js v4.
Code base is not udpated.
(textlint work on Node.js v4 for a little while)

**Comment by 0x6b** [comment]
@azu, I have no problem about dropping old Node versions according to their maintenance schedule. But I think not all of textlint users are Node.js programmer—they have been just using Node.js for textlint—so they might not aware of Node.js release cycle. It'd be good for such users to get end of support date as early as possible to prevent their daily workflow running under unsupported version. My quick thoughts include:

- Update README and textlint.github.io to announce v4 end of support
- Update textlint cli to warn end of support date

I think I'm thinking too much 😟  (or too enterprisey?) Your comments would be appreciated.

**Comment by azu** [comment]
> But I think not all of textlint users are Node.js programmer

Yes.
Main purpose of this issue is that drop Node.js v4 from `.travis.yml`.
Of course, To show warning is helpful for user.
(`engines` field of pacakge.json is helpful)
Because, Some rule has required Node.js >=6 like `textlint-rule-no-dead-link`.

> Update README and textlint.github.io to announce v4 end of support

Yeah, We can improve Install(requirements) secion on https://github.com/textlint/textlint#installation

> Update textlint cli to warn end of support date

We are careful about that implementation.
Because, `textlint`'s stdout is used by other CLI.

For example, some user use `textlint` as follows:

```
# unix pipe
textlint -f json | jq "."
```

Probably, we should add meta data like `{ name: "stylish", forMachine: false }` to [getFormatterList()](https://github.com/textlint/textlint/blob/master/packages/textlint-formatter/src/index.ts#L50 "getFormatterList()") and [getFixerFormatterList()](https://github.com/textlint/textlint/blob/master/packages/textlint-fixer-formatter/src/index.ts#L52 "getFixerFormatterList()") before to show warning.

**Comment by azu** [comment]
I've removed Node.js 4 from Travis CI.
Because, it block CI..
https://github.com/textlint/textlint/pull/507/commits/0c49f0bb183b2bcc428d5b0ba8ff92449e142559
