### ISSUE TITLE
test(textlint-formatter): `mocha` runs fine while `tsc` cannot compile the script

### ISSUE THREAD

**Issue by 0x6b** [textlint/textlint#448]
**What version of textlint are you using?**

Current tip of the master (0bb11b6778f49ecdb07292c2c564a4b76b7aa8b5)

**What did you do? Please include the actual source code causing the issue.**

I just found that my WebStorm shows red sign on `textlint-formatter-test.ts` even though I just finished all tests (`yarn run test:all`) on fresh docker image with success.

**What did you expect to happen?**

`textlint-formatter-test.ts` should fail.

**What actually happened? Please include the actual, raw output from textlint.**

After quick look here you can see simple scenario—`mocha` runs fine while `tsc` cannot compile the script.

```sh
$ cd packages/textlint-formatter
$ $(npm bin)/tsc -p test
test/textlint-formatter-test.ts(21,42): error TS2345: Argument of type '{ filePath: string; messages: { type: string; ruleId: string; line: number; column: number; index...' is not assignable to parameter of type 'TextlintResult[]'.
  Type '{ filePath: string; messages: { type: string; ruleId: string; line: number; column: number; index...' is not assignable to type 'TextlintResult'.
    Types of property 'messages' are incompatible.
      Type '{ type: string; ruleId: string; line: number; column: number; index: number; message: string; }[]' is not assignable to type 'TextlintMessage[]'.
        Type '{ type: string; ruleId: string; line: number; column: number; index: number; message: string; }' is not assignable to type 'TextlintMessage'.
          Property 'severity' is missing in type '{ type: string; ruleId: string; line: number; column: number; index: number; message: string; }'.
test/textlint-formatter-test.ts(55,42): error TS2345: Argument of type '({ filePath: string; messages: { type: string; ruleId: string; line: number; column: number; inde...' is not assignable to parameter of type 'TextlintResult[]'.
  Type '{ filePath: string; messages: { type: string; ruleId: string; line: number; column: number; index...' is not assignable to type 'TextlintResult'.
    Type '{ filePath: string; messages: { type: string; ruleId: string; line: number; column: number; index...' is not assignable to type 'TextlintResult'.
      Types of property 'messages' are incompatible.
        Type '{ type: string; ruleId: string; line: number; column: number; index: number; message: string; }[]' is not assignable to type 'TextlintMessage[]'.
          Type '{ type: string; ruleId: string; line: number; column: number; index: number; message: string; }' is not assignable to type 'TextlintMessage'.
            Property 'severity' is missing in type '{ type: string; ruleId: string; line: number; column: number; index: number; message: string; }'.
```

```sh
$ $(npm bin)/mocha test/textlint-formatter-test.ts


  textlint-formatter-test
    createFormatter
      ✓ should return formatter function (51ms)
      ✓ run all formatter (217ms)
      formatter
        ✓ should return output text
    getFormatterList
      ✓ should return list of formatter(s)


  4 passing (291ms)
```

Added `cache: false` to [`test/ts-setup.js`](https://github.com/textlint/textlint/blob/0bb11b6778f49ecdb07292c2c564a4b76b7aa8b5/packages/textlint-formatter/test/ts-setup.js) following [ts-node Configuration Options](https://github.com/TypeStrong/ts-node#configuration-options) but no clue.

Commit 139c7cbaf85506a4c7771b32fd9f4d736910857f changed `TextlintMessage` interface and made `severity` property [not optional](https://github.com/textlint/textlint/commit/139c7cbaf85506a4c7771b32fd9f4d736910857f#diff-d686a97daacd3bd8e8b66d37dcde7ae3L190). Since [`textlint-formatter-test.ts`](https://github.com/textlint/textlint/blob/0bb11b6778f49ecdb07292c2c564a4b76b7aa8b5/packages/textlint-formatter/test/textlint-formatter-test.ts) does not specify `severity` it should fail. It might be due to my setup or steps to test, and also changing the test is easy, but I would like to know why this happens.

**Comment by azu** [comment]
Fmm, It is strange.

I found two points that is related with this isssue.

### `ts-node` disable `type-check` by default!
 
> --fast is the default behaviour now, use --type-check for type checking behaviour

[Release "Fast" By Default · TypeStrong/ts-node](https://github.com/TypeStrong/ts-node/releases/tag/v4.0.0 "Release &#34;Fast&#34; By Default · TypeStrong/ts-node")

I mistrust it 👻 

### `ts-node` does not support `paths` field of `tsconfig.json`.

It means that `$(npm bin)/tsc -p test` use `textlint/src/*`, But `$(npm bin)/mocha test/textlint-formatter-test.ts` use `textlint/lib/*` (compiled).

- [tsconfig.json/paths not working with ts-node · Issue #138 · TypeStrong/ts-node](https://github.com/TypeStrong/ts-node/issues/138#issuecomment-349222070)
- [Add paths support by jonaskello · Pull Request #254 · TypeStrong/ts-node](https://github.com/TypeStrong/ts-node/pull/254#issuecomment-269404787)

[tsconfig-paths](https://www.npmjs.com/package/tsconfig-paths "tsconfig-paths") workaround.

[tsconfig-paths](https://www.npmjs.com/package/tsconfig-paths "tsconfig-paths") make `ts-node` work with `paths`.

```
yarn add --dev tsconfig-paths
```

and add `-r tsconfig-paths/register` to `mocha.opts`.

**Comment by 0x6b** [comment]
@azu, appreciate your analysis as always. Oh my type check...added `typeCheck: false` to `test/ts-setup.js` and got compilation error as expected. Since `$(npm bin)/tsc -p test` is for reproducible purpose only, I will work on modifying `ts-setup.js` first. I think we have to review other packages' setup as well.
