### ISSUE TITLE
Revisit mocha setup

### ISSUE THREAD

**Issue by 0x6b** [textlint/textlint#451]
We found that, in some situation, `mocha` runs fine while `tsc` cannot compile TypeScript test cases (issue #448 and pull request #449). We have to review current setup for each packages and make changes needed in order to improve credibility/stability of tests.

- [x] [`packages/@textlint/ast-node-types/test/ts-setup.js`](https://github.com/textlint/textlint/blob/79c931fa85801e44bf669a4a98c61945949a2c15/packages/%40textlint/ast-node-types/test/ts-setup.js)
- [x] [`packages/@textlint/ast-traverse/test/ts-setup.js`](https://github.com/textlint/textlint/blob/79c931fa85801e44bf669a4a98c61945949a2c15/packages/%40textlint/ast-traverse/test/ts-setup.js)
- [x] [`packages/@textlint/fixer-formatter/test/ts-setup.js`](https://github.com/textlint/textlint/blob/79c931fa85801e44bf669a4a98c61945949a2c15/packages/%40textlint/fixer-formatter/test/ts-setup.js)
- [x] [`packages/@textlint/kernel/test/ts-setup.js`](https://github.com/textlint/textlint/blob/79c931fa85801e44bf669a4a98c61945949a2c15/packages/%40textlint/kernel/test/ts-setup.js)
- [x] [`packages/@textlint/linter-formatter/test/ts-setup.js`](https://github.com/textlint/textlint/blob/79c931fa85801e44bf669a4a98c61945949a2c15/packages/%40textlint/linter-formatter/test/ts-setup.js)
- [x] [`packages/textlint-tester/test/ts-setup.js`](https://github.com/textlint/textlint/blob/79c931fa85801e44bf669a4a98c61945949a2c15/packages/textlint-tester/test/ts-setup.js)
- [x] [`packages/textlint/test/ts-setup.js`](https://github.com/textlint/textlint/blob/79c931fa85801e44bf669a4a98c61945949a2c15/packages/textlint/test/ts-setup.js)

As @azu said at https://github.com/textlint/textlint/pull/449#issuecomment-355722411, [Jest](https://facebook.github.io/jest/) is one of options.

Edit: add list of `ts-setup.js` for review.
Edit 2: update list as some packages are moved to `@textlint` by #455

**Comment by azu** [comment]
📝 Jest example

- [One vs. many — Why we moved from multiple git repos to a monorepo and how we set it up](https://hackernoon.com/one-vs-many-why-we-moved-from-multiple-git-repos-to-a-monorepo-and-how-we-set-it-up-f4abb0cfe469 "One vs. many — Why we moved from multiple git repos to a monorepo and how we set it up")

**Comment by azu** [comment]
ts-jest has same problem 😢 
[Type error reporting · Issue #79 · kulshekhar/ts-jest](https://github.com/kulshekhar/ts-jest/issues/79 "Type error reporting · Issue #79 · kulshekhar/ts-jest")

**Comment by azu** [comment]
I've created  a loader package that extends `ts-node`.

- [azu/ts-node-test-register: Load from `test/tsconfig.json` with ts-node.](https://github.com/azu/ts-node-test-register "azu/ts-node-test-register: Load from `test/tsconfig.json` with ts-node.")

We can replace `ts-setup.js` with `ts-node-test-register`.

**Comment by 0x6b** [comment]
@azu, thanks for the new module. I'll try.
