### ISSUE TITLE
website: help page

### ISSUE THREAD

**Issue by azu** [textlint/textlint#470]
Need some follow up #468 

https://textlint.netlify.com/help.html

- Replace `documentation on this site` link to "getting-started`
   - Forget to replace the `index` link
- Add "Contributing Guide" link to help page
   - Looks like [Docusaurus  help page](https://docusaurus.io/en/help.html "Docusaurus · Easy to Maintain Open Source Documentation Websites")

📝 We can also include `contributing` to sidebar like React

![image](https://user-images.githubusercontent.com/19714/34946559-b4f6a9c2-fa4a-11e7-92e5-1cd28ef31a0e.png)
https://reactjs.org/docs/how-to-contribute.html

**Comment by 0x6b** [comment]
@azu, I had to update the help as well... Please review my pull request #471.
