### ISSUE TITLE
textlint-tester: incorrect `main` and `types` declaration?

### ISSUE THREAD

**Issue by 0x6b** [textlint/textlint#475]
While I'm walking around the codebase in order to find candidate for TypeScript-ify, I found following in the `textlint-tester/package.json`:

https://github.com/textlint/textlint/blob/b769c1bbd0f60623e1c1d2cea53ad2a977179956/packages/textlint-tester/package.json#L20-L21

I think it should be:

```
 "main": "lib/textlint-tester/src/index.js", 
 "types": "lib/textlint-tester/src/index.d.ts", 
```

Any thoughts?

**Comment by azu** [comment]
Opps. This is a bug.

**Comment by azu** [comment]
Side note: we need to E2E test for textlint-tester.

**Comment by 0x6b** [comment]
@azu, thanks for prompt response and pull request!

**Comment by 0x6b** [comment]
Side note (2): how about sorting `package.json` using [`sort-package-json`](https://www.npmjs.com/package/sort-package-json)? It will enable us find such inconsistency more easily.

$ yarn lerna exec npx sort-package-json

If it's ok for you, I will open an issue and pull request.

**Comment by azu** [comment]
Yes! 
I use `sort-package-json` in locally (just in setup)
