### ISSUE TITLE
markdown-to-ast cannot parse query string correctly

### ISSUE THREAD

**Issue by Leko** [textlint/textlint#513]
**What version of textlint are you using?**

@textlint/markdown-to-ast@6.0.5

**What file type (Markdown, plain text, etc.) are you using?**

Markdown

**What did you do? Please include the actual source code causing the issue.**

I try to parse this string

```md
- [はい](./hoge.html?x=0&not=1)
```

It is parse result (excluded loc and range).

```json
{
  "type": "Link",
  "title": null,
  "url": "./hoge.html?x=0¬=1",
  "children": [
    {
      "type": "Str",
      "value": "はい",
      "raw": "はい"
    }
  ],
  "raw": "[はい](./hoge.html?x=0&not=1)"
}
```

`url` is unexpected to me.
What is `¬`?

I try to reproduce this issue, maybe reproduce it when url contains `&not`

**What did you expect to happen?**

```json
{
  "type": "Link",
  "title": null,
  "url": "./hoge.html?x=0&not=1",
  "children": [
    {
      "type": "Str",
      "value": "はい",
      "raw": "はい"
    }
  ],
  "raw": "[はい](./hoge.html?x=0&not=1)"
}
```

**Comment by azu** [comment]
latest [remark](https://github.com/wooorm/remark) parse this correctly.

https://astexplorer.net/#/gist/0a92bbf654aca4fdfb3f139254cf0bad/ffe102014c188434c027e43661dbe6ec30042ee2

I think that we can resolve this issue by updating  [remark](https://github.com/wooorm/remark)?

**Comment by Leko** [comment]
@azu That’s good news.
I’ll try to update remark. Thanks.
