### ISSUE TITLE
yarn prettier does not work on Windows

### ISSUE THREAD

**Issue by otariidae** [textlint/textlint#544]
**What did you do? Please include the actual source code causing the issue.**
When I was working on developing, I ran `yarn prettier`.

**What did you expect to happen?**
I expected `yarn prettier` worked well,

**What actually happened? Please include the actual, raw output from textlint.**

`yarn prettier` threw an error.

```
~\textlint>yarn prettier
yarn run v1.9.2
$ prettier --write 'packages/**/*.{js,jsx,ts,tsx,css}'
[error] No matching files. Patterns tried: 'packages/**/*.{js,jsx,ts,tsx,css}' !**/node_modules/** !./node_modules/**
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I tried some patterns in package.json to fix it: 
`    "prettier": "prettier --write 'packages/**/*.{js,jsx,ts,tsx,css}'",` : Single quotes (current version). This does not work.
`    "prettier": "prettier --write packages/**/*.{js,jsx,ts,tsx,css}",` : No quotes. This works.
`    "prettier": "prettier --write \"packages/**/*.{js,jsx,ts,tsx,css}\"",` : Escaped double quotes. This also works.

tried in Command Prompt on latest version of Windows10. I don't know how these patterns work on Mac and Linux.

**Comment by azu** [comment]
> Escaped double quotes.

Thanks. Escaped double quotes is correct.

https://github.com/eslint/eslint/issues/5796#issuecomment-206765069
