### ISSUE TITLE
textlint doesn't produce output for org-mode files (.org file extension)

### ISSUE THREAD

**Issue by robstewart57** [textlint/textlint#555]
**What version of textlint are you using?**

v11.0.1

**What file type (Markdown, plain text, etc.) are you using?**

org-mode markup.

**What did you do? Please include the actual source code causing the issue.**

Run `textlint` on `file.org`.

**What did you expect to happen?**

A non-empty report.

**What actually happened? Please include the actual, raw output from textlint.**

The `file.org` content is:

    Mistakes were made.

Running `npx textlint --rule write-good file.org` returns no output.

Given the same file contents for a `file.txt` file, i.e. with a filename ending in `.txt`, `textlint` returns:

    1:10  error  "were made" may be passive voice  write-good

Why does `textlint` return different outputs for these two files?

**Comment by azu** [comment]
I don't know textlint plugin for org-mode file, but [@textlint/textlint-plugin-text](https://github.com/textlint/textlint/tree/master/packages/%40textlint/textlint-plugin-text) support `extension` option.

You can lint `.org` file as `txt` file by following configuration.

`.textlintrc`:
```json
{
    "plugins": {
        "@textlint/text": {
            "extensions": [".org"]
        }
    }
}
```

- [Configuring textlint · textlint](https://textlint.github.io/docs/configuring.html)

**Comment by robstewart57** [comment]
Thanks, that's helpful.

Is there a way to define `"extensions": [".org"]` as a `textlint` command flag if `--plugin @textlint/text` is given, rather than in a `.textlintrc` file?

**Comment by azu** [comment]
Close - This will be 3rd-party plugin.
