### ISSUE TITLE
Automatically apply parser plugins using filename extensions

### ISSUE THREAD

**Issue by robstewart57** [textlint/textlint#556]
**What version of textlint are you using?**

v11.0.1

**What file type (Markdown, plain text, etc.) are you using?**

LaTeX.

**What did you do? Please include the actual source code causing the issue.**

    textlint  --rule write-good file.tex

**What did you expect to happen?**

- __Expectation__: no output.
- __Feature request__: apply the `latex` textlint plugin before applying the rules.

**What actually happened? Please include the actual, raw output from textlint.**

If I run:

    textlint  --rule write-good --plugin=latex file.tex

Then I get an output:

    24:6  error  "just" can weaken meaning  write-good

The feature request is this: could textlint predict the syntax of the file content using the `.tex` filename extension, apply `--plugin=latex` automatically, then process the files contents and produce a report.

**Comment by azu** [comment]
Thanks for request.

textlint's policy is that less built-in plugins and less built-in rules.
As a result, textlint does not have built-in rules.
(Built-in `text` and `markdown` plugin come from history reason…)

So, we not want to add built-in plugin.

Sorry.
