### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by azu** [textlint/textlint#56]
We need logo and icon for oraganization.#55

**Comment by azu** [comment]
haywire logo

<img width="500" alt="textlint-logo" src="https://cloud.githubusercontent.com/assets/19714/10908427/4bd99566-8275-11e5-9167-5ffa09f72409.png">

- psd https://monosnap.com/file/QTQamPqnVu1F8SMsVAAI7vn5oqhyYM.png
- logoist https://monosnap.com/file/brDdHdCsYkxQ5lBN6LGCKVchdpDg3h

We need more better logo...

**Comment by uetchy** [comment]
I have some idea.
![artboard 8 copy 2](https://cloud.githubusercontent.com/assets/431808/11435034/f89640fa-9518-11e5-9bee-fcacf9446667.png)
This logo featuring a nib.

**Comment by uetchy** [comment]
![artboard 8 copy](https://cloud.githubusercontent.com/assets/431808/11435062/676c5a1e-9519-11e5-99b9-b5d65b7b36ff.png)
Or like this?

**Comment by uetchy** [comment]
This is based on first idea.
![artboard 8 copy 3](https://cloud.githubusercontent.com/assets/431808/11435094/9fdeffe6-9519-11e5-92f0-9a660648bdbf.png)

**Comment by azu** [comment]
@uetchy Oh, Thanks.
I like this https://github.com/textlint/textlint/issues/56#issuecomment-160050653

フォントのバランスが一番しっくりきました。

**Comment by uetchy** [comment]
@azu OK. I attached a .sketch file contains all those logos.

https://www.dropbox.com/s/265wbvlwsuk0yel/textlint-logo.sketch?dl=0

You can use this file to modify logo for adapting to any situation.
Also you can modify fonts if you don't have Avenir and Avenir Next.
If you don't have [Sketch](https://www.sketchapp.com), please tell me and I'll convert the file into any file format you want.

Or should I push .sketch file to somewhere on Github?

**Comment by azu** [comment]
@uetchy Thanks. (I didn't have Sketch, I installed sketch trial ver)
I created [textlint/media](https://github.com/textlint/media "textlint/media") repostiory and invited @uetchy to textlint org!
if you will, please pull-request logo to this repository.

Similar approach:

- [power-assert-js/power-assert-js-logo](https://github.com/power-assert-js/power-assert-js-logo "power-assert-js/power-assert-js-logo")
- [jser/media](https://github.com/jser/media "jser/media")

**Comment by uetchy** [comment]
Thank you for inviting me to textlint team!
I joined on textlint/media and created [PR](https://github.com/textlint/media/pull/1) for logo draft.
Please check this out.

**Comment by azu** [comment]
https://github.com/textlint/media/pull/1 is merged and close this issue.

![logo](https://cloud.githubusercontent.com/assets/19714/12647544/0046da90-c619-11e5-9aad-b7ab635fac04.png)

Thanks.
