### ISSUE TITLE
Reduce unnecessary dependencies(Node 6>=)

### ISSUE THREAD

**Issue by azu** [textlint/textlint#585]
textlint support Node.js 6 >=.( We plan to drop Node.js 6 in addition #600 )
So, we can use native function without polyfill.
For example, we can use `Object.assign` instead of `object-assign` module.

## Tasks

- [x] use `Object.assign` instead of `object-assign` module. #618 
  - or, just use `{ ...object }` spread syntax
- [x] use `Promise` instead of `bluebird`
  - need to check performance regiression, but it is minor problem.

**Comment by ia17011** [comment]
I'm looking around the issues on this project to find the task I can work on. 
I think this task is already closed by above #618 #672.

**Comment by azu** [comment]
Thanks!
We can close it.
