### ISSUE TITLE
Creating our own exclusion list for textlint-rule-spelling EN

### ISSUE THREAD

**Issue by donganzh** [textlint/textlint#603]
@takahashim @azu @nodaguti Hi! In the .textlintrc file, how do we configure the skip pattern item so that it will exclude multiple words instead of just one? Is that the correct way to add an exclusion words list for this spelling check tool? Thanks!

**Comment by azu** [comment]
This is textlint-rule-spelling's issue, is not textlint issue.

Duplicate of https://github.com/ta2gch/textlint-rule-spelling/issues/1
