### ISSUE TITLE
Can I get more information of TypeofTxtNode<T> (TypeScript)?

### ISSUE THREAD

**Issue by anchan828** [textlint/textlint#627]
I would like to request for updating TypeofTxtNode type (TypeScript).

**What version of textlint are you using?**

v11.3.1
**What file type (Markdown, plain text, etc.) are you using?**

Markdown
**What did you do? Please include the actual source code causing the issue.**

I got node as ASTNodeTypes.Link. And cast node to TypeofTxtNode<ASTNodeTypes.Link>

```
const linkNode = node as TypeofTxtNode<ASTNodeTypes.Link>;
```
However TypeofTxtNode<ASTNodeTypes.Link> always returns `TxtParentNode`, So I can't get information for ASTNodeTypes.Link

[![Screenshot from Gyazo](https://gyazo.com/d2b52e6b07f3dae7e72b14a905404f62/raw)](https://gyazo.com/d2b52e6b07f3dae7e72b14a905404f62)

**What did you expect to happen?**
I can access to url property, but type is **any**

[![Screenshot from Gyazo](https://gyazo.com/cd146be65f104f65dfcd233c064475e4/raw)](https://gyazo.com/cd146be65f104f65dfcd233c064475e4)

**What actually happened? Please include the actual, raw output from textlint.**

**Comment by azu** [comment]
Unfortunately, current [TxtAST](https://github.com/textlint/textlint/blob/bc57614fc7d89e0829f270d02834bbbf0f876dfc/docs/txtnode.md#type) define only `TxtParentNode`(Parent) and `TxtTextNode`(Child) node.
It does not defined `TxtLinkNode`. 
`TypeofTxtNode` type function just return Parent or Child.

So, `url` property to be `any` type.

It is historical reason
[Common type](https://github.com/textlint/textlint/blob/bc57614fc7d89e0829f270d02834bbbf0f876dfc/docs/txtnode.md#type) of TxtNode come from Markdown parser. However textlint support any parser by plugin.
So, I have not defined specific node `@textlint/ast-node-types`.
(we have treated these like LinkNode as implementation-defined type)

But, It is reasonable that we add [Common type](https://github.com/textlint/textlint/blob/bc57614fc7d89e0829f270d02834bbbf0f876dfc/docs/txtnode.md#type)(`TxtLinkNode` type etc..) definitions to `@textlint/ast-node-types`.

**Comment by azu** [comment]
[textlint v13.0.0](https://textlint.github.io/blog/2023/01/27/textlint-13.html) improve this and close this issue
