### ISSUE TITLE
Feature request for "textlint" config in package.json

### ISSUE THREAD

**Issue by trevordmiller** [textlint/textlint#643]
The https://textlint.github.io/docs/configuring.html docs show that textlint can be configured with various types of `.textlintrc*` files. It would be nice if a `textlint` config could be used in the `package.json` as well to keep configuration contained to package.json for users that like to do that. For example, [Prettier has the `prettier` key as well as all the `.prettierrc*` options](https://prettier.io/docs/en/configuration.html). This seems to be common for many other npm packages (ESLint, lint-staged, husky, etc). using [cosmiconfig which supports all these different configurations automatically](https://github.com/davidtheclark/cosmiconfig).

**Comment by azu** [comment]
Yes.
https://github.com/azu/rc-config-loader#api also support `packageJSON` option.

**Comment by azu** [comment]
📝 I've noticed that rc-config-loader's type definition is wrong.
This fixes is released as patch https://github.com/azu/rc-config-loader/releases/tag/2.0.5

**Comment by trevordmiller** [comment]
@azu Cool! I've submitted a PR for it: https://github.com/textlint/textlint/pull/644

**Comment by azu** [comment]
I've released https://github.com/textlint/textlint/releases/tag/textlint%4011.5.0
