### ISSUE TITLE
Feature request for "recommended" preset

### ISSUE THREAD

**Issue by trevordmiller** [textlint/textlint#647]
Many other linting tools have "recommended" presets that catch errors (rather than opinionated things) like:

- `eslint` has `eslint:recommended`
- `eslint-plugin-react` has `react/recommended`
- `eslint-plugin-jsx-a11y` has `jsx-a11y/recommended`

etc.

It would be nice if textlint had a "recommended" preset with language-agnostic plugins that prevent errors like:

```
textlint-rule-no-dead-link
textlint-rule-spellchecker
```

So that less manual configuration is needed for a error preventing / non-opinionated setup.

**Comment by azu** [comment]
textlint support multiple languages.
It is difficult to define recommended.
