### ISSUE TITLE
How to always use the latest version of textlint preset

### ISSUE THREAD

**Issue by amimas** [textlint/textlint#663]
This isn't a feature request or a bug fix. Technically this is an npm related question but I'm posting it here because it's somewhat related to textlint usage.

I have several independent repositories for documentation. I'm using textlint in all of those repositories and I want to centralize the configuration so that I don't need to manually change the configs in all of those repositories. The preset feature of textlint is going to help with this for sure.

For example, let's say I have the following independent repositories where some are for documentation:

- my-org-name/textlint-preset-my-org-name
- my-org-name/repo-a
- my-org-name/repo-b
- my-org-name/repo-c

I can create a textlint preset with necessary rules/configurations. However, even with the preset, I will still need to go to each repositories and update the version number of the preset to the latest released preset.

Is there anything else I can do so that when I make an update in the `textlint-preset-my-org-name`, those changes will be immediately available in `repo-a`, `repo-b`, and `repo-c`?

In the dependencies of those repos, I could probably set the textlint-preset dependency to be the latest, but wouldn't that impact the package lock file?

Any suggestions?

**Comment by azu** [comment]
Following web servicer provide that automatic update dependencies feature.

* [Whitesource Renovate - Automated Dependency Updates](https://renovate.whitesourcesoftware.com/)
* [Dependabot](https://dependabot.com/)
  - It is GitHub 
* [Whitesource Renovate - Automated Dependency Updates](https://renovate.whitesourcesoftware.com/)
* [Dependabot](https://dependabot.com/)

Some user use these services.

In personal, I use Renovate that provide flexible configuration.

**Comment by amimas** [comment]
Thanks for the suggestions. I'll look into those.
