### ISSUE TITLE
Migrate mocha.opts to mocharc.json

### ISSUE THREAD

**Issue by azu** [textlint/textlint#672]
mocha@7 deprecated `mocha.opts`.
We need to migrate mocha.opts to mocharc.json.

I've created migration script https://github.com/azu/mocha-migrate

##  Task

- [ ] Upgrade to Mocha@7 Probably already done?
- [ ] Migrate mocha.opts to mocharc.json

Useful oneliner:

```
./node_modules/.bin/lerna exec --no-bail npx @azu/mocha-migrate migrate-opts -- -file test/mocha.opts -type json -rm
```

## Related

- [Migrate mocha.opts to .mocharc.(json|js|yml|yaml) · Issue #125 · secretlint/secretlint](https://github.com/secretlint/secretlint/issues/125)

**Comment by numb86** [comment]
I forgot to write `resolve #672` when I made the PR, but I think this issue can be closed.
I think #585 can close for the same reason too.
