### ISSUE TITLE
types are capital case, while https://github.com/syntax-tree/mdast#heading and gatsby use small case. 

### ISSUE THREAD

**Issue by stevemarksd** [textlint/textlint#678]
Is this intended?

For example on gatsby I get `heading` while with this library I get `Heading`.

**Comment by azu** [comment]
Its historial reason. 
textlint used another parse library instead of marked at first.

Also, We have recommended to use constants variable like `Syntax.Str` instead of "str"
Rule creator should use constants variables.

It is diffcult to change the value without breaking rules.
