### ISSUE TITLE
Enabling color in piped output (stylish formatter)

### ISSUE THREAD

**Issue by tueda** [textlint/textlint#721]
**What version of textlint are you using?**

v11.7.6

**What file type (Markdown, plain text, etc.) are you using?**

Markdown

**What did you do? Please include the actual source code causing the issue.**

Piped textlint output to another process.

**What did you expect to happen?**

Expected that the output is colorized.

**What actually happened? Please include the actual, raw output from textlint.**

Even without the `--no-color` option, it seems that the stylish formatter stop colorizing when piped (the 2nd execution in the screenshot below).

![textlint-screenshot](https://user-images.githubusercontent.com/1481665/100533451-b4a96800-3247-11eb-9726-60ab1226d336.png)

I guess this is a bug. If not, is there any way to force-enable color for piped output?

Might be related to #593, if Gradle uses pipes for output of child processes (I'm not sure).

**Comment by azu** [comment]
> I guess this is a bug. If not, is there any way to force-enable color for piped output?

textlint just use [chalk](https://github.com/chalk/chalk).

`FORCE_COLOR=1` env enable color.
FORCE_COLOR is the config of chalk https://github.com/chalk/chalk#chalksupportscolor

```
FORCE_COLOR=1 ./node_modules/.bin/textlint README.md | cat
```

Probably related issue?

- [colors not showing up after spawning child process · Issue #381 · chalk/chalk](https://github.com/chalk/chalk/issues/381)

I do not know what natural behavior in this case.

For example, I want to disable color in the following case by default.

```
$ ./node_modules/.bin/textlint README.md > a.txt
```

**Comment by tueda** [comment]
I see. Maybe having something like `--always-color` option would be helpful. But indeed, setting `FORCE_COLOR=1` does work for me. Thank you.

**Comment by azu** [comment]
`textlint --color` is the same feature as `FORCE_COLOR`.
But, it is implicitly and it is not easy to understand.
