### ISSUE TITLE
Feature suggestion: Inclusion of Just Not Sorry

### ISSUE THREAD

**Issue by BrandonKMLee** [textlint/textlint#750]
Observing https://github.com/defmethodinc/just-not-sorry would this be a good feature lint?

**Comment by azu** [comment]
You can create a rule using [just-not-sorry/src/warnings/phrases.json](https://github.com/defmethodinc/just-not-sorry/blob/a0109fee25a3d120979a5c1862fcd1b6b0c37d6c/src/warnings/phrases.json)

Docs: https://textlint.github.io/docs/rule.html

textlint's core does not includes rule as built-in.
