### ISSUE TITLE
[feat] Can you please provide `sync` API with `async` together?

### ISSUE THREAD

**Issue by JounQin** [textlint/textlint#756]
All APIs changed to be `async` in #75, but it would be great to still support legacy `sync` APIs.

I'm trying to integrate this tool to ESLint which does not support `async` rule for now.

So my proposal is to add `lintTextSync`, `fixTextSync` APIs, etc.

Some async rules like `textlint-rule-no-dead-link` won't work for `sync` API, that's OK, the user should just disable `async` rules if they want to use `sync` API.

If you agree, I'm glad to raise a PR for it.

**Comment by azu** [comment]
I will not plan that implement sync API.
It will make some inconsistency(Parallel linting, async rule which you suggested) and It will grow maintenance cost.

ESLint will support async API in the future.
https://github.com/eslint/rfcs/pull/42
In another way, [sync-rpc](https://github.com/ForbesLindesay/sync-rpc) may helps you.(I've not tested)

Also, [textlint-rule-eslint](https://github.com/textlint-rule/textlint-rule-eslint) integrate with ESLint.

**Comment by JounQin** [comment]
> ESLint will support async API in the future.

Yes, but it requires a long time to go.

> In another way, sync-rpc may helps you.(I've not tested)

Thanks for this suggestion, I'll give it a try.

> Also, textlint-rule-eslint integrate with ESLint.

It aims different things as my purpose, it runs ESLint for JavaScript codes just like `eslint-plugin-markdown`.

But what I'm doing is run `textlint` for all files as an ESLint plugin.

**Comment by JounQin** [comment]
> It will make some inconsistency(Parallel linting, async rule which you suggested) and It will grow maintenance cost.

Many tools support `async/sync` at the same time, and most of the logic codes could be shared.

[unified#process](https://github.com/unifiedjs/unified#processorprocessfile-done)
[unified#processSync](https://github.com/unifiedjs/unified#processorprocesssyncfilevalue)

[cosmiconfig#async](https://github.com/davidtheclark/cosmiconfig#asynchronous-api)
[cosmiconfig#sync](https://github.com/davidtheclark/cosmiconfig#synchronous-api)

**Comment by JounQin** [comment]
@azu I'm doing similar things for `markuplint` at the same time: https://github.com/markuplint/markuplint/pull/155

We can test `async` and `sync` rules at the same time easily [like above PR](https://github.com/markuplint/markuplint/pull/155/files#diff-da134c4f21dea4a1f06463a604536add39bd2bf0c815698b76f35ee58f86959aR23-R50).

**Comment by azu** [comment]
Comparing cosmiconfig is not fair.
That is the library. textlint is not a library.

unified support async plugin, but it just throws an Error on `runSync`.

```js
var vfile = require("vfile");
var unified = require("unified");
var f = vfile("alpha");
var n = { type: "bravo" };
var e = { type: "charlie" };
const file = unified().use(plugin).runSync(n, f);
console.log(file);

function plugin() {
    return transformer;
}

async function transformer(tree, file) {
    console.log(tree, file);
    return e;
}
```

> Error: `runSync` finished async. Use `run` instead

https://runkit.com/azu/6083a90f2912a2001a3a1fe8

In my experience, 20~30% of rules use async API.
Especially, almost 40~50% use async API in Japanese rules.
(These rules load a large dictionary like [kuromojin](https://github.com/azu/kuromojin))

Sync to async is easy, but the reverse is difficult.
I concern that sync API will be debt and I not want to implement/maintenance Sync API.

Thanks for suggestion.

**Comment by JounQin** [comment]
> Error: runSync finished async. Use run instead

Yes, I've mentioned:

> Some async rules like textlint-rule-no-dead-link won't work for sync API, that's OK, the user should just disable async rules if they want to use sync API.

---

> I concern that sync API will be debt and I not want to implement/maintenance Sync API.

That's unfortunately if you've decided that.

Or may I raise a PR first to see how difficult would it cost? That's OK if you decided not to merge that.

**Comment by azu** [comment]
> Or may I raise a PR first to see how difficult would it cost? That's OK if you decide not to merge that even.

Yes! 
It is good that discusses on implementation.

**Comment by azu** [comment]
Closed by https://github.com/textlint/textlint/pull/757#issuecomment-835364621
