### ISSUE TITLE
types: getSource argument type is wrong

### ISSUE THREAD

**Issue by azu** [textlint/textlint#770]
https://github.com/textlint/textlint/blob/cd9adbe7b63ea688a73372f0e6e4fa36bfe0332a/packages/@textlint/types/src/Rule/BaseRuleContext.ts#L45

```diff
- getSource(node: TxtNode, beforeCount?: number, afterCount?: number): string
+ getSource(node?: TxtNode, beforeCount?: number, afterCount?: number): string
```

is correct.

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue

**Comment by azu** [comment]
Yes welcome!
