### ISSUE TITLE
Change target:es5 to modern outputs

### ISSUE THREAD

**Issue by azu** [textlint/textlint#774]
textlint does not aim to support IE that requires es5.
Previously, textlint-scripts drop to support ES5 env.

- https://github.com/textlint/textlint-scripts/issues/28

So, we can change the basic `target` property in tsconfig.json

https://github.com/textlint/textlint/blob/1c989818942059353b8f7eb5dd190835b5cf2ef5/tsconfig.base.json#L11

What is the version suitable?

## Purpose

- make output for modern browser and modern Node.js
  - It will optimize runtime

**Comment by azu** [comment]
https://github.com/tsconfig/bases#recommended-tsconfigjson recommended is es2015

**Comment by teppeis** [comment]
- es2020 for Node v14+
- es2019 for Node v12+
- es2018 for Node v10+

ref. https://node.green/
