### ISSUE TITLE
Fix `files` field

### ISSUE THREAD

**Issue by azu** [textlint/textlint#782]
Current

```
  "files": [
            "bin/",
            "lib/",
            "module/",
            "src/"
   ],
```

it should be 

```diff
  "files": [
            "bin/",
            "lib/",
            "module/",
            "src/",
+           "!*.tsbuildinfo"
   ],
```

Currently, `tsbuildinfo` file is included in the distributions files.
We do not want to includes it.

📝 `tsbuildinfo` is TypeScript build cache.

## Check

You can check the included files via `npm pack` command.

```
npm pack
```

**Comment by azu** [comment]
`.npmignore` may be simple for this case.

**Comment by RhnSharma** [comment]
I would like to take this one.
