### ISSUE TITLE
use native `Map` instead or `map-like`

### ISSUE THREAD

**Issue by azu** [textlint/textlint#792]
https://github.com/textlint/textlint/search?q=map-like

We have used [map-like](https://github.com/azu/map-like) for compatibility ES5 env.
However, we have dropped ES5 env supports in [textlint v12.0.0](https://textlint.github.io/blog/2021/05/24/textlint-12.html).

So, We can just use `Map` instead or `map-like`.

## Task

- [ ] use native `Map` instead or `map-like`
- [ ] Remove `ma-like` dependencies

**Comment by RhnSharma** [comment]
I would like to take this one.

**Comment by RhnSharma** [comment]
I would like to take this one.
