### ISSUE TITLE
.textlintignore is ignoring glob pattern

### ISSUE THREAD

**Issue by prisis** [textlint/textlint#804]
**What version of textlint are you using?**
v12.0.2
**What file type (Markdown, plain text, etc.) are you using?**
Markdown, plain text, etc.
**What did you do? Please include the actual source code causing the issue.**
I added `node_modules/**/*.md` to `.textlintignore` because im using textlint in a monorepro.
**What did you expect to happen?**
I expected that all paths with node_modules/** would be ignored.
**What actually happened? Please include the actual, raw output from textlint.**
Command that was run `textlint ./packages/**/README.md ./README.md ./UPGRADE.md --parallel --debug`

Repository url https://github.com/anolilab/javascript-style-guide

<details>
<summary>Debug Log</summary>
<pre>
textlint:cli textlint --version: 12.0.2 +0ms
  textlint:cli Running on files, stdin-filename: undefined +1ms
  textlint:cli textlint --parallel +0ms
  textlint:module-loader config Config {
  textlint:module-loader   configFile: '/private/anolilab/.textlintrc',
  textlint:module-loader   rulesBaseDirectory: undefined,
  textlint:module-loader   disabledRules: [],
  textlint:module-loader   rules: [
  textlint:module-loader     'en-capitalization',
  textlint:module-loader     'footnote-order',
  textlint:module-loader     'no-todo',
  textlint:module-loader     'no-dead-link',
  textlint:module-loader     'no-empty-section',
  textlint:module-loader     'terminology',
  textlint:module-loader     'apostrophe',
  textlint:module-loader     'diacritics',
  textlint:module-loader     '@textlint-rule/no-invalid-control-character',
  textlint:module-loader     '@textlint-rule/no-unmatched-pair',
  textlint:module-loader     'abbr-within-parentheses',
  textlint:module-loader     'alex',
  textlint:module-loader     'write-good',
  textlint:module-loader     'common-misspellings'
  textlint:module-loader   ],
  textlint:module-loader   disabledFilterRules: [],
  textlint:module-loader   filterRules: [],
  textlint:module-loader   presets: [ '@textlint-rule/google' ],
  textlint:module-loader   plugins: [],
  textlint:module-loader   pluginsConfig: {},
  textlint:module-loader   rulesConfig: {
  textlint:module-loader     '@textlint-rule/google/abbreviations': true,
  textlint:module-loader     '@textlint-rule/google/articles': true,
  textlint:module-loader     '@textlint-rule/google/capitalization': true,
  textlint:module-loader     '@textlint-rule/google/clause-order': true,
  textlint:module-loader     '@textlint-rule/google/colons': true,
  textlint:module-loader     '@textlint-rule/google/commas': true,
  textlint:module-loader     '@textlint-rule/google/contractions': true,
  textlint:module-loader     '@textlint-rule/google/dashes': true,
  textlint:module-loader     '@textlint-rule/google/ellipses': true,
  textlint:module-loader     '@textlint-rule/google/exclamation-points': true,
  textlint:module-loader     '@textlint-rule/google/hyphens': true,
  textlint:module-loader     '@textlint-rule/google/plurals-parentheses': true,
  textlint:module-loader     '@textlint-rule/google/possessives': true,
  textlint:module-loader     '@textlint-rule/google/quotation-marks': true,
  textlint:module-loader     '@textlint-rule/google/sentence-spacing': true,
  textlint:module-loader     '@textlint-rule/google/slashes': true,
  textlint:module-loader     '@textlint-rule/google/tone': true,
  textlint:module-loader     '@textlint-rule/google/word-list': true,
  textlint:module-loader     'en-capitalization': true,
  textlint:module-loader     'footnote-order': true,
  textlint:module-loader     'no-todo': true,
  textlint:module-loader     'no-dead-link': { ignore: [Array] },
  textlint:module-loader     'no-empty-section': true,
  textlint:module-loader     terminology: { defaultTerms: false, terms: [Array] },
  textlint:module-loader     apostrophe: true,
  textlint:module-loader     diacritics: true,
  textlint:module-loader     '@textlint-rule/no-invalid-control-character': true,
  textlint:module-loader     '@textlint-rule/no-unmatched-pair': true,
  textlint:module-loader     'abbr-within-parentheses': true,
  textlint:module-loader     alex: { allow: [Array] },
  textlint:module-loader     'write-good': { passive: false, eprime: false },
  textlint:module-loader     'common-misspellings': true
  textlint:module-loader   },
  textlint:module-loader   filterRulesConfig: {},
  textlint:module-loader   rulePaths: [],
  textlint:module-loader   formatterName: undefined,
  textlint:module-loader   quiet: false,
  textlint:module-loader   color: true,
  textlint:module-loader   cache: false,
  textlint:module-loader   cacheLocation: '/private/anolilab/javascript-style-guide/.textlintcache',
  textlint:module-loader   ignoreFile: '/private/anolilab/javascript-style-guide/.textlintignore'
  textlint:module-loader } +0ms
  textlint:module-loader Loading rules from /private/anolilab/javascript-style-guide/node_modules/textlint-rule-en-capitalization/lib/textlint-rule-en-capitalization.js +3ms
  textlint:module-loader Loading rules from /private/anolilab/javascript-style-guide/node_modules/textlint-rule-footnote-order/lib/textlint-rule-footnote-order.js +0ms
  textlint:module-loader Loading rules from /private/anolilab/javascript-style-guide/node_modules/textlint-rule-no-todo/lib/no-todo.js +1ms
  textlint:module-loader Loading rules from /private/anolilab/javascript-style-guide/node_modules/textlint-rule-no-dead-link/lib/no-dead-link.js +1ms
  textlint:module-loader Loading rules from /private/anolilab/javascript-style-guide/node_modules/textlint-rule-no-empty-section/lib/textlint-rule-no-empty-section.js +23ms
  textlint:module-loader Loading rules from /private/anolilab/javascript-style-guide/node_modules/textlint-rule-terminology/index.js +2ms
  textlint:module-loader Loading rules from /private/anolilab/javascript-style-guide/node_modules/textlint-rule-apostrophe/index.js +13ms
  textlint:module-loader Loading rules from /private/anolilab/javascript-style-guide/node_modules/textlint-rule-diacritics/index.js +0ms
  textlint:module-loader Loading rules from /private/anolilab/javascript-style-guide/node_modules/@textlint-rule/textlint-rule-no-invalid-control-character/lib/textlint-rule-no-invalid-control-character.js +1ms
  textlint:module-loader Loading rules from /private/anolilab/javascript-style-guide/node_modules/@textlint-rule/textlint-rule-no-unmatched-pair/lib/textlint-rule-no-unmatched-pair.js +1ms
  textlint:module-loader Loading rules from /private/anolilab/javascript-style-guide/node_modules/textlint-rule-abbr-within-parentheses/lib/textlint-rule-abbr-within-parentheses.js +2ms
  textlint:module-loader Loading rules from /private/anolilab/javascript-style-guide/node_modules/textlint-rule-alex/lib/textlint-rule-alex.js +1ms
  textlint:module-loader Loading rules from /private/anolilab/javascript-style-guide/node_modules/textlint-rule-write-good/lib/write-good.js +88ms
  textlint:module-loader Loading rules from /private/anolilab/javascript-style-guide/node_modules/textlint-rule-common-misspellings/lib/common-misspellings.js +5ms
  textlint:module-loader Loading rules from preset: /private/anolilab/javascript-style-guide/node_modules/@textlint-rule/textlint-rule-preset-google/lib/textlint-rule-preset-google.js +2ms
  textlint:module-loader config Config {
  textlint:module-loader   configFile: '/private/anolilab/.textlintrc',
  textlint:module-loader   rulesBaseDirectory: undefined,
  textlint:module-loader   disabledRules: [],
  textlint:module-loader   rules: [
  textlint:module-loader     'en-capitalization',
  textlint:module-loader     'footnote-order',
  textlint:module-loader     'no-todo',
  textlint:module-loader     'no-dead-link',
  textlint:module-loader     'no-empty-section',
  textlint:module-loader     'terminology',
  textlint:module-loader     'apostrophe',
  textlint:module-loader     'diacritics',
  textlint:module-loader     '@textlint-rule/no-invalid-control-character',
  textlint:module-loader     '@textlint-rule/no-unmatched-pair',
  textlint:module-loader     'abbr-within-parentheses',
  textlint:module-loader     'alex',
  textlint:module-loader     'write-good',
  textlint:module-loader     'common-misspellings'
  textlint:module-loader   ],
  textlint:module-loader   disabledFilterRules: [],
  textlint:module-loader   filterRules: [],
  textlint:module-loader   presets: [ '@textlint-rule/google' ],
  textlint:module-loader   plugins: [],
  textlint:module-loader   pluginsConfig: {},
  textlint:module-loader   rulesConfig: {
  textlint:module-loader     '@textlint-rule/google/abbreviations': true,
  textlint:module-loader     '@textlint-rule/google/articles': true,
  textlint:module-loader     '@textlint-rule/google/capitalization': true,
  textlint:module-loader     '@textlint-rule/google/clause-order': true,
  textlint:module-loader     '@textlint-rule/google/colons': true,
  textlint:module-loader     '@textlint-rule/google/commas': true,
  textlint:module-loader     '@textlint-rule/google/contractions': true,
  textlint:module-loader     '@textlint-rule/google/dashes': true,
  textlint:module-loader     '@textlint-rule/google/ellipses': true,
  textlint:module-loader     '@textlint-rule/google/exclamation-points': true,
  textlint:module-loader     '@textlint-rule/google/hyphens': true,
  textlint:module-loader     '@textlint-rule/google/plurals-parentheses': true,
  textlint:module-loader     '@textlint-rule/google/possessives': true,
  textlint:module-loader     '@textlint-rule/google/quotation-marks': true,
  textlint:module-loader     '@textlint-rule/google/sentence-spacing': true,
  textlint:module-loader     '@textlint-rule/google/slashes': true,
  textlint:module-loader     '@textlint-rule/google/tone': true,
  textlint:module-loader     '@textlint-rule/google/word-list': true,
  textlint:module-loader     'en-capitalization': true,
  textlint:module-loader     'footnote-order': true,
  textlint:module-loader     'no-todo': true,
  textlint:module-loader     'no-dead-link': { ignore: [Array] },
  textlint:module-loader     'no-empty-section': true,
  textlint:module-loader     terminology: { defaultTerms: false, terms: [Array] },
  textlint:module-loader     apostrophe: true,
  textlint:module-loader     diacritics: true,
  textlint:module-loader     '@textlint-rule/no-invalid-control-character': true,
  textlint:module-loader     '@textlint-rule/no-unmatched-pair': true,
  textlint:module-loader     'abbr-within-parentheses': true,
  textlint:module-loader     alex: { allow: [Array] },
  textlint:module-loader     'write-good': { passive: false, eprime: false },
  textlint:module-loader     'common-misspellings': true
  textlint:module-loader   },
  textlint:module-loader   filterRulesConfig: {},
  textlint:module-loader   rulePaths: [],
  textlint:module-loader   formatterName: undefined,
  textlint:module-loader   quiet: false,
  textlint:module-loader   color: true,
  textlint:module-loader   cache: false,
  textlint:module-loader   cacheLocation: '/private/anolilab/javascript-style-guide/.textlintcache',
  textlint:module-loader   ignoreFile: '/private/anolilab/javascript-style-guide/.textlintignore'
  textlint:module-loader } +1ms
  textlint:find-util findFiles ignore baseDir: /private/anolilab/javascript-style-guide, normalizeIgnoreFilePath: /private/anolilab/javascript-style-guide/.textlintignore +0ms
  textlint:find-util ignored: [ '/private/anolilab/javascript-style-guide/**/node_modules/**/*.md', '/private/anolilab/javascript-style-guide/packages/babel-preset/node_modules/**/*.md', '/private/anolilab/javascript-style-guide/packages/browserslist-config-anolilab/node_modules/**/*.md', '/private/anolilab/javascript-style-guide/packages/eslint-config/node_modules/**/*.md', '/private/anolilab/javascript-style-guide/packages/prettier-config/node_modules/**/*.md', '/private/anolilab/javascript-style-guide/packages/stylelint-config/node_modules/**/*.md', '/private/anolilab/javascript-style-guide/packages/textlint-config/node_modules/**/*.md', '/private/anolilab/javascript-style-guide/packages/babel-preset/LICENSE.md', '/private/anolilab/javascript-style-guide/packages/browserslist-config-anolilab/LICENSE.md', '/private/anolilab/javascript-style-guide/packages/eslint-config/LICENSE.md', '/private/anolilab/javascript-style-guide/packages/prettier-config/LICENSE.md', '/private/anolilab/javascript-style-guide/packages/stylelint-config/LICENSE.md', '/private/anolilab/javascript-style-guide/packages/textlint-config/LICENSE.md', '/private/anolilab/javascript-style-guide/packages/babel-preset/CHANGELOG.md', '/private/anolilab/javascript-style-guide/packages/browserslist-config-anolilab/CHANGELOG.md', '/private/anolilab/javascript-style-guide/packages/eslint-config/CHANGELOG.md', '/private/anolilab/javascript-style-guide/packages/prettier-config/CHANGELOG.md', '/private/anolilab/javascript-style-guide/packages/stylelint-config/CHANGELOG.md', '/private/anolilab/javascript-style-guide/packages/textlint-config/CHANGELOG.md' ] +1ms
  textlint:find-util search patterns: [ 'packages/babel-preset/README.md', 'packages/babel-preset/node_modules/@babel/cli/README.md', 'packages/babel-preset/node_modules/@babel/core/README.md', 'packages/babel-preset/node_modules/@babel/core/node_modules/@babel/helper-compilation-targets/README.md', 'packages/babel-preset/node_modules/@babel/core/node_modules/@babel/helper-member-expression-to-functions/README.md', 'packages/babel-preset/node_modules/@babel/core/node_modules/@babel/helper-module-imports/README.md', 'packages/babel-preset/node_modules/@babel/core/node_modules/@babel/helper-module-transforms/README.md', 'packages/babel-preset/node_modules/@babel/core/node_modules/@babel/helper-optimise-call-expression/README.md', 'packages/babel-preset/node_modules/@babel/core/node_modules/@babel/helper-replace-supers/README.md', 'packages/babel-preset/node_modules/@babel/core/node_modules/@babel/helper-simple-access/README.md', 'packages/babel-preset/node_modules/@babel/core/node_modules/@babel/helper-split-export-declaration/README.md', 'packages/babel-preset/node_modules/@babel/core/node_modules/@babel/helper-validator-identifier/README.md', 'packages/babel-preset/node_modules/@babel/helper-compilation-targets/README.md', 'packages/babel-preset/node_modules/@babel/helper-create-class-features-plugin/README.md', 'packages/babel-preset/node_modules/@babel/helper-create-regexp-features-plugin/README.md', 'packages/babel-preset/node_modules/@babel/helper-define-polyfill-provider/README.md', 'packages/babel-preset/node_modules/@babel/helper-define-polyfill-provider/node_modules/@babel/helper-module-imports/README.md', 'packages/babel-preset/node_modules/@babel/helper-define-polyfill-provider/node_modules/@babel/helper-plugin-utils/README.md', 'packages/babel-preset/node_modules/@babel/helper-get-function-arity/README.md', 'packages/babel-preset/node_modules/@babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining/README.md', 'packages/babel-preset/node_modules/@babel/plugin-proposal-async-generator-functions/README.md', 'packages/babel-preset/node_modules/@babel/plugin-proposal-class-properties/README.md', 'packages/babel-preset/node_modules/@babel/plugin-proposal-class-static-block/README.md', 'packages/babel-preset/node_modules/@babel/plugin-proposal-decorators/README.md', 'packages/babel-preset/node_modules/@babel/plugin-proposal-dynamic-import/README.md', 'packages/babel-preset/node_modules/@babel/plugin-proposal-export-namespace-from/README.md', 'packages/babel-preset/node_modules/@babel/plugin-proposal-json-strings/README.md', 'packages/babel-preset/node_modules/@babel/plugin-proposal-logical-assignment-operators/README.md', 'packages/babel-preset/node_modules/@babel/plugin-proposal-nullish-coalescing-operator/README.md', 'packages/babel-preset/node_modules/@babel/plugin-proposal-numeric-separator/README.md', 'packages/babel-preset/node_modules/@babel/plugin-proposal-object-rest-spread/README.md', 'packages/babel-preset/node_modules/@babel/plugin-proposal-object-rest-spread/node_modules/@babel/helper-compilation-targets/README.md', 'packages/babel-preset/node_modules/@babel/plugin-proposal-object-rest-spread/node_modules/@babel/helper-validator-option/README.md', 'packages/babel-preset/node_modules/@babel/plugin-proposal-optional-catch-binding/README.md', 'packages/babel-preset/node_modules/@babel/plugin-proposal-optional-chaining/README.md', 'packages/babel-preset/node_modules/@babel/plugin-proposal-private-methods/README.md', 'packages/babel-preset/node_modules/@babel/plugin-proposal-private-property-in-object/README.md', 'packages/babel-preset/node_modules/@babel/plugin-proposal-unicode-property-regex/README.md', 'packages/babel-preset/node_modules/@babel/plugin-syntax-async-generators/README.md', 'packages/babel-preset/node_modules/@babel/plugin-syntax-async-generators/node_modules/@babel/helper-plugin-utils/README.md', 'packages/babel-preset/node_modules/@babel/plugin-syntax-bigint/README.md', 'packages/babel-preset/node_modules/@babel/plugin-syntax-bigint/node_modules/@babel/helper-plugin-utils/README.md', 'packages/babel-preset/node_modules/@babel/plugin-syntax-class-properties/README.md', 'packages/babel-preset/node_modules/@babel/plugin-syntax-class-properties/node_modules/@babel/helper-plugin-utils/README.md', 'packages/babel-preset/node_modules/@babel/plugin-syntax-class-static-block/README.md', 'packages/babel-preset/node_modules/@babel/plugin-syntax-decorators/README.md', 'packages/babel-preset/node_modules/@babel/plugin-syntax-dynamic-import/README.md', 'packages/babel-preset/node_modules/@babel/plugin-syntax-dynamic-import/node_modules/@babel/helper-plugin-utils/README.md', 'packages/babel-preset/node_modules/@babel/plugin-syntax-export-namespace-from/README.md', 'packages/babel-preset/node_modules/@babel/plugin-syntax-export-namespace-from/node_modules/@babel/helper-plugin-utils/README.md', 'packages/babel-preset/node_modules/@babel/plugin-syntax-json-strings/README.md', 'packages/babel-preset/node_modules/@babel/plugin-syntax-json-strings/node_modules/@babel/helper-plugin-utils/README.md', 'packages/babel-preset/node_modules/@babel/plugin-syntax-jsx/README.md', 'packages/babel-preset/node_modules/@babel/plugin-syntax-jsx/node_modules/@babel/helper-plugin-utils/README.md', 'packages/babel-preset/node_modules/@babel/plugin-syntax-logical-assignment-operators/README.md', 'packages/babel-preset/node_modules/@babel/plugin-syntax-logical-assignment-operators/node_modules/@babel/helper-plugin-utils/README.md', 'packages/babel-preset/node_modules/@babel/plugin-syntax-nullish-coalescing-operator/README.md', 'packages/babel-preset/node_modules/@babel/plugin-syntax-nullish-coalescing-operator/node_modules/@babel/helper-plugin-utils/README.md', 'packages/babel-preset/node_modules/@babel/plugin-syntax-numeric-separator/README.md', 'packages/babel-preset/node_modules/@babel/plugin-syntax-numeric-separator/node_modules/@babel/helper-plugin-utils/README.md', 'packages/babel-preset/node_modules/@babel/plugin-syntax-object-rest-spread/README.md', 'packages/babel-preset/node_modules/@babel/plugin-syntax-object-rest-spread/node_modules/@babel/helper-plugin-utils/README.md', 'packages/babel-preset/node_modules/@babel/plugin-syntax-optional-catch-binding/README.md', 'packages/babel-preset/node_modules/@babel/plugin-syntax-optional-catch-binding/node_modules/@babel/helper-plugin-utils/README.md', 'packages/babel-preset/node_modules/@babel/plugin-syntax-optional-chaining/README.md', 'packages/babel-preset/node_modules/@babel/plugin-syntax-optional-chaining/node_modules/@babel/helper-plugin-utils/README.md', 'packages/babel-preset/node_modules/@babel/plugin-syntax-private-property-in-object/README.md', 'packages/babel-preset/node_modules/@babel/plugin-syntax-top-level-await/README.md', 'packages/babel-preset/node_modules/@babel/plugin-syntax-typescript/README.md', 'packages/babel-preset/node_modules/@babel/plugin-syntax-typescript/node_modules/@babel/helper-plugin-utils/README.md', 'packages/babel-preset/node_modules/@babel/plugin-transform-arrow-functions/README.md', 'packages/babel-preset/node_modules/@babel/plugin-transform-async-to-generator/README.md', 'packages/babel-preset/node_modules/@babel/plugin-transform-block-scoped-functions/README.md', 'packages/babel-preset/node_modules/@babel/plugin-transform-block-scoping/README.md', 'packages/babel-preset/node_modules/@babel/plugin-transform-classes/README.md', 'packages/babel-preset/node_modules/@babel/plugin-transform-computed-properties/README.md', 'packages/babel-preset/node_modules/@babel/plugin-transform-destructuring/README.md', 'packages/babel-preset/node_modules/@babel/plugin-transform-dotall-regex/README.md', 'packages/babel-preset/node_modules/@babel/plugin-transform-duplicate-keys/README.md', 'packages/babel-preset/node_modules/@babel/plugin-transform-exponentiation-operator/README.md', 'packages/babel-preset/node_modules/@babel/plugin-transform-for-of/README.md', 'packages/babel-preset/node_modules/@babel/plugin-transform-function-name/README.md', 'packages/babel-preset/node_modules/@babel/plugin-transform-jscript/README.md', 'packages/babel-preset/node_modules/@babel/plugin-transform-literals/README.md', 'packages/babel-preset/node_modules/@babel/plugin-transform-member-expression-literals/README.md', 'packages/babel-preset/node_modules/@babel/plugin-transform-modules-amd/README.md', 'packages/babel-preset/node_modules/@babel/plugin-transform-modules-commonjs/README.md', 'packages/babel-preset/node_modules/@babel/plugin-transform-modules-systemjs/README.md', 'packages/babel-preset/node_modules/@babel/plugin-transform-modules-umd/README.md', 'packages/babel-preset/node_modules/@babel/plugin-transform-named-capturing-groups-regex/README.md', 'packages/babel-preset/node_modules/@babel/plugin-transform-new-target/README.md', 'packages/babel-preset/node_modules/@babel/plugin-transform-object-super/README.md', 'packages/babel-preset/node_modules/@babel/plugin-transform-parameters/README.md', 'packages/babel-preset/node_modules/@babel/plugin-transform-property-literals/README.md', 'packages/babel-preset/node_modules/@babel/plugin-transform-property-mutators/README.md', 'packages/babel-preset/node_modules/@babel/plugin-transform-react-display-name/README.md', 'packages/babel-preset/node_modules/@babel/plugin-transform-react-display-name/node_modules/@babel/helper-plugin-utils/README.md', 'packages/babel-preset/node_modules/@babel/plugin-transform-react-jsx/README.md', 'packages/babel-preset/node_modules/@babel/plugin-transform-react-jsx/node_modules/@babel/helper-annotate-as-pure/README.md', 'packages/babel-preset/node_modules/@babel/plugin-transform-react-jsx/node_modules/@babel/helper-module-imports/README.md', ... 53 more items ] +0ms
  textlint:find-util search ignore patterns: [ '**/.git/**', '**/node_modules/**', '/private/anolilab/javascript-style-guide/**/node_modules/**/*.md', '/private/anolilab/javascript-style-guide/packages/babel-preset/node_modules/**/*.md', '/private/anolilab/javascript-style-guide/packages/browserslist-config-anolilab/node_modules/**/*.md', '/private/anolilab/javascript-style-guide/packages/eslint-config/node_modules/**/*.md', '/private/anolilab/javascript-style-guide/packages/prettier-config/node_modules/**/*.md', '/private/anolilab/javascript-style-guide/packages/stylelint-config/node_modules/**/*.md', '/private/anolilab/javascript-style-guide/packages/textlint-config/node_modules/**/*.md', '/private/anolilab/javascript-style-guide/packages/babel-preset/LICENSE.md', '/private/anolilab/javascript-style-guide/packages/browserslist-config-anolilab/LICENSE.md', '/private/anolilab/javascript-style-guide/packages/eslint-config/LICENSE.md', '/private/anolilab/javascript-style-guide/packages/prettier-config/LICENSE.md', '/private/anolilab/javascript-style-guide/packages/stylelint-config/LICENSE.md', '/private/anolilab/javascript-style-guide/packages/textlint-config/LICENSE.md', '/private/anolilab/javascript-style-guide/packages/babel-preset/CHANGELOG.md', '/private/anolilab/javascript-style-guide/packages/browserslist-config-anolilab/CHANGELOG.md', '/private/anolilab/javascript-style-guide/packages/eslint-config/CHANGELOG.md', '/private/anolilab/javascript-style-guide/packages/prettier-config/CHANGELOG.md', '/private/anolilab/javascript-style-guide/packages/stylelint-config/CHANGELOG.md', '/private/anolilab/javascript-style-guide/packages/textlint-config/CHANGELOG.md' ] +2ms
</pre>
</details>

**Comment by azu** [comment]
>`textlint ./packages/**/README.md ./README.md ./UPGRADE.md --parallel --debug`

This glob pattern is expanded by shell like bash.

You need to wrap glob with quote like `"`.

```
$ textlint "./packages/**/README.md" ./README.md ./UPGRADE.md --parallel --debug
```

Currently, `.textlintignore` does not ignore direct specify like `$ textlint node_modules/ignored_path_but_direct_specify/README.md`.

This looks like similar behavior to ESLint.
https://eslint.org/docs/user-guide/configuring/ignoring-code#ignored-file-warnings 

cc @frozenbonito

**Comment by azu** [comment]
close. please reopen if this issue was not resolved.
