### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by benmccann** [textlint/textlint#816]
The link on https://github.com/textlint/markdown-to-ast is broken

It should instead point to https://github.com/textlint/textlint/tree/master/packages/%40textlint/markdown-to-ast

**Comment by azu** [comment]
Can you submit a Pull Request to fix this issue?

**Comment by benmccann** [comment]
Unfortunately I can't because the repo has been archived. It would need to be temporarily unarchived, updated, and then rearchived, which means only an admin can do it

**Comment by azu** [comment]
Ah, I misunderstood this issue.

I've fixed the link on https://github.com/textlint/markdown-to-ast

Thanks for report!
