### ISSUE TITLE
textlint-tester: type mismatch

### ISSUE THREAD

**Issue by azu** [textlint/textlint#820]
When I've create a rule and test it.

https://github.com/textlint-rule/textlint-rule-no-duplicate-abbr/blob/0e496443352a451d17f04526893ba1c10c60eaf3/src/textlint-rule-no-duplicate-abbr.ts#L4-L12

TypeScript throw an compiler error on textlint-tester.

```
TS2345: Argument of type 'TextlintRuleReporter<Options>' is not assignable to parameter of type 'TextlintRuleModule<{}> | TestConfig'.   Type 'TextlintRuleReporter<Options>' is not assignable to type 'TextlintRuleReporter<{}>'.     Property 'allowAbbrList' is missing in type '{}' but required in type 'Options'.
```

We need to fix textlint-tester typing.

**Comment by stmtk1** [comment]
Compile successed. I don't understand what problem is.

**Comment by azu** [comment]
It will be fixed.
