### ISSUE TITLE
Install plugins/rules from given .textlintrc configuration file

### ISSUE THREAD

**Issue by raphaelstolt** [textlint/textlint#825]
It would be nice to have a single source of configuration i.e. `.textlintrc`. So that a given `.textlintrc` configuration file would also define the rulesets to be installed. Therefor the textlint CLI could have an additional option e.g. `--install-rules` which takes the configured rules from the configuration file and installs the corresponding rule npm packages.

Didn't find a similar issue for this feature request, so feel free to close this one if it's a duplicate.

**Comment by azu** [comment]
Closed. Feel free to re-open if this isssue was not resolved
