### ISSUE TITLE
How can I ignore markdown files?

### ISSUE THREAD

**Issue by ItzMiracleOwO** [textlint/textlint#830]
**What version of textlint are you using?**

**What file type (Markdown, plain text, etc.) are you using?**
MarkDown

**What did you do? Please include the actual source code causing the issue.**
-

**What did you expect to happen?**
-

**What actually happened? Please include the actual, raw output from textlint.**
-

**Comment by azu** [comment]
Can you means that you not want to lint markdown file?
textlint  process markdown and text file by default. (It is historical reason)

You can avoid this behavior by following options.

Using [.textlintignore](https://textlint.github.io/docs/ignore.html#ignoring-files-textlintignore) file:

```
*.md
```

Using arguments to specify extensions

```
textlint /path/to/dir/*.your-target-ext
```
