### ISSUE TITLE
Column count does not respect display width

### ISSUE THREAD

**Issue by ernix** [textlint/textlint#852]
source: https://vim-jp.slack.com/archives/CJMV3MSLR/p1646725321428869

**What version of textlint are you using?**

```
% textlint -v
v12.1.1
```

**What file type (Markdown, plain text, etc.) are you using?**

plain text

**What did you do? Please include the actual source code causing the issue.**

```
% npm install -g textlint
% npm install -g textlint-rule-no-nfd
% echo 'こんにちわーると゛' | textlint --no-textlintrc --stdin --rule no-nfd --format unix
% echo 'こんにち🍣わーると゛' | textlint --no-textlintrc --stdin --rule no-nfd --format unix
```

**What did you expect to happen?**

```
% echo 'こんにちわーると゛' | textlint --no-textlintrc --stdin --rule no-nfd --format unix
<text>:1:17: Disallow to use NFD(well-known as UTF8-MAC 濁点): "と゛" => "ど" [Error/no-nfd]

1 problem
```

```
% echo 'こんにち🍣わーると゛' | textlint --no-textlintrc --stdin --rule no-nfd --format unix
<text>:1:19: Disallow to use NFD(well-known as UTF8-MAC 濁点): "と゛" => "ど" [Error/no-nfd]

1 problem
```

**What actually happened? Please include the actual, raw output from textlint.**

```
% echo 'こんにちわーると゛' | textlint --no-textlintrc --stdin --rule no-nfd --format unix
<text>:1:9: Disallow to use NFD(well-known as UTF8-MAC 濁点): "と゛" => "ど" [Error/no-nfd]

1 problem
```

```
% echo 'こんにち🍣わーると゛' | textlint --no-textlintrc --stdin --rule no-nfd --format unix
<text>:1:11: Disallow to use NFD(well-known as UTF8-MAC 濁点): "と゛" => "ど" [Error/no-nfd]

1 problem
```

---

Like other major text editors, vim has `makeprg` and `errorformat` options to browse errors provided by an external program in quickfix-window so that we can jump to exact error positions.  The problem is, it counts col position as how it displayed in window. There are only two items `%c` (hard-tab as 1 char) and `%v` (hard-tab as 8 char) to handle column position.

I'm not sure how textlint count columns but at least it seems like assuming both of Japanese wide characters and ASCII characters as 1, Emojis are 2.

I would appreciate it if textlint has options like `--count-visual-width`, to respect Unicode character width property.  It may includes headaches due to Ambiguous Character Width though.

**Comment by azu** [comment]
`column` is not related to display width. That is based on index value of the line(JavaScript uses UTF-16's Code unit)
The index value is column value + 1.

e.g. 
```js
'こんにち🍣わーると゛'[9 + 1]; // =>  ゛
```

📝 The `column` come from [JS AST API](https://gist.github.com/azu/8866b2cb9b7a933e01fe) and [Error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error) object 

I think that custom formatter is best of position for this issue.
https://textlint.github.io/docs/formatter.html

For example, [pretty-error](https://github.com/textlint/textlint/blob/master/packages/%40textlint/linter-formatter/src/formatters/pretty-error.ts) treat the display width.

<img width="697" alt="image" src="https://user-images.githubusercontent.com/19714/157235925-e061a460-7bc2-4287-ae2b-a1197da87169.png">


[textlint's core](https://github.com/textlint/textlint/tree/master/packages/%40textlint/kernel) does not treat display things.(The output `column` value is computed in the core)

**Comment by ernix** [comment]
I ended up writing a wrapper script to mimic `--format unix`:
https://gist.github.com/ernix/f190b2c1a8b7a933abf44eff80a0648a

Thanks anyway.
