### ISSUE TITLE
Plugin example in document has a mistake?

### ISSUE THREAD

**Issue by matori** [textlint/textlint#858]
Plugin example codes are written like this.

```js
export default class TextProcessor {
    constructor(options = {}) {
        this.options = options;
        // support "extension" option
        this.extensions = this.config.extensions ? this.config.extensions : [];
    }
//...
}
```
https://github.com/textlint/textlint/blob/master/docs/plugin.md?plain=1#L34-L37

A name of constructor argument is `options`, however, extensions option refer to `config`.
It looks like a small mistake.

If use `options`, `this.config.extensions` should be `this.options.extensions`, or use `config`, a name of constructor argument should be `config`.

**Comment by azu** [comment]
Thanks. You're right, this document is wrong.

We should change to following.

```diff
-    constructor(options = {}) {
-        this.options = options;
+   constructor(config = {}) {
+       this.config = config;
        // support "extension" option
        this.extensions = this.config.extensions ? this.config.extensions : [];
```

https://github.com/textlint/textlint/blob/b22545462a0f65ed59f27d11434e93dd10cfe4dd/packages/%40textlint/textlint-plugin-markdown/src/MarkdownProcessor.ts#L10-L12

**Comment by matori** [comment]
I appreciate your hard work!
