### ISSUE TITLE
expose TextlintPluginPreProcessResult/TextlintPluginPostProcessResult type

### ISSUE THREAD

**Issue by azu** [textlint/textlint#873]
These types should be exposed from @textlint/types.

https://github.com/textlint/textlint/blob/ae8900485daf2564e738bd14c00e6edc62e2d32e/packages/%40textlint/types/src/Plugin/TextlintPluginModule.ts#L12-L13

Entry point

- https://github.com/textlint/textlint/blob/ae8900485daf2564e738bd14c00e6edc62e2d32e/packages/%40textlint/types/src/index.ts

## TODO

- export TextlintPluginPreProcessResult/TextlintPluginPostProcessResult from https://github.com/textlint/textlint/blob/ae8900485daf2564e738bd14c00e6edc62e2d32e/packages/%40textlint/types/src/index.ts

**Comment by shogohida** [comment]
@azu 
Hi, Azu, can I work on this?

**Comment by azu** [comment]
@shogohida Yes, welcome!

**Comment by shogohida** [comment]
@azu 
I created a pull request so please review it when you have time!

https://github.com/textlint/textlint/pull/920
