### ISSUE TITLE
Install `--global` contradicts reccomendation

### ISSUE THREAD

**Issue by bramses** [textlint/textlint#885]
On the [Installation section of the README](https://github.com/textlint/textlint#installation), the installation command is: 

```
$ npm install textlint --global
```

However, a few lines below, the library recommends:  
> We recommend installing `textlint` locally.

Most people will install globally after copy/pasting and not read past to this reccomendation.

Suggestion: remove `--global` from README

**Comment by azu** [comment]
I agree with you.

Probably, we need to use `npm install textlint --save-dev` on the documention by default like https://eslint.org/

**Comment by Uda-Titor** [comment]
@azu 
Thanks for the advice.
I made the change based on your advice.
