### ISSUE TITLE
Missing dependency from @textlint/markdown-to-ast to mdast-util-gfm-autolink-literal

### ISSUE THREAD

**Issue by alexeagle** [textlint/textlint#903]
This require statement at HEAD
https://github.com/textlint/textlint/blob/a69c0a79a371a64117b21287b41603dd193b9624/packages/%40textlint/markdown-to-ast/src/parse-markdown.ts#L3
depends on a library that's not a declared dependency:
https://github.com/textlint/textlint/blob/a69c0a79a371a64117b21287b41603dd193b9624/packages/%40textlint/markdown-to-ast/package.json#L37-L46

It only happens to work for some users because that dependency is hoisted by the package manager to a place that node resolves it.
This can be reproduced by adding `hoist=false` to `.npmrc` and running under `pnpm`.

**Comment by azu** [comment]
> import autolinkLiteral from "mdast-util-gfm-autolink-literal/from-markdown";

This line is a workaround for remark issue.
https://github.com/remarkjs/remark-gfm/issues/16
remark-gfm does not provide a option for disabling that missing `position` property issue.

However, we need to fix  implicit dependencies issue.

I'm not too familiar with pnpm behavior. Probably, we need to add `mdast-util-gfm-autolink-literal` to peerDeps or deps?

**Comment by alexeagle** [comment]
thanks for looking @azu - I think the principled answer is to add a regular `dependency` on that package, since you depend on it and don't expect that a user of this package should be expected to have installed it themselves.

FYI as a workaround I added
`public-hoist-pattern[]=mdast-util-gfm-autolink-literal`
to .npmrc for now, so that it can be require'd from anywhere.

**Comment by azu** [comment]
Fixed in https://github.com/textlint/textlint/releases/tag/v12.2.2
