### ISSUE TITLE
File globbing in package.json gives incorrect results

### ISSUE THREAD

**Issue by uetchy** [textlint/textlint#92]
When I passed following files to textlint with `textlint content/**/*.md`, it correctly checks all of Markdown files.

```
├── content
│   ├── about.md
│   └── post
│       ├── 2013-07-07-install-julius-with-homebrew.md
│       ├── 2013-11-05-osx-http-proxy.md
│       ├── 2013-12-05-qiita-alfred-workflow.md
```

But when it comes to the script section in `package.json`, it began to returning result with missing __about.md__.

So I made workaround:
```json
"scripts": {
  "test": "textlint content/post/*.md content/*.md"
}
```

I don't know whether or not this is the issue of textlint.
This is standard behaviour?

Thanks in advance.

**Comment by azu** [comment]
@uetchy Thanks for report.

`content/**/*.md` is not handled by textlint.
`npm run` via `/bin/sh` expand `content/**/*.md` to `content/post/about.md content/post/....md` that doesn't contain `content/readme.md`

You try this behavior on ` /bin/sh`.

```
/bin/sh
ls content/**/*.md
```

As a result, `textlint content/**/*.md`  == `textlint content/about.md content/post/....md` 

Currently, `textlint` support `"path/to/file.md"` or `"path/to/dir"` (not support wildcard).
We want to support `$ textlint "content/post/*.md"` if possible.

wordkaround

```
find ./content -name '*.md' | xargs textlint
```
or 

Run textlint via task runner like [gulp-textlint](https://github.com/textlint/gulp-textlint "gulp-textlint").

**Comment by uetchy** [comment]
ok I got it.
I'll try `find ./content -name '*.md' | xargs textlint`.

By the way, I discovered this trick now:

```shell
sh-3.2$ ls content/{,*/}*.md
content/about.md
content/post/2013-07-07-install-julius-with-homebrew.md
```

This would be another workaround I think.
Anyway thank you for surveying this issue!
