### ISSUE TITLE
TextLintTester skips the test string when it has leading whitespace.

### ISSUE THREAD

**Issue by er-ri** [textlint/textlint#956]
Hi

Many thanks for your work!

Currently, I am working on a textlint rule. 
While in the testing phase, I found that the TextLintTester will skip the string that has leading spaces.

The phenomenon can also be reproduced with `textlint-rule-no-todo` when `column` and `line` were not specified.

The following code shows the test cases and the results.
As you can see the second test case was not passed even though it contains 'TODO'.

```nodejs
        {
            text: "TODO: this is TODO",
            errors: [
                {
                    message: "Found TODO: 'TODO: this is TODO'"
                }
            ]
        },
        {
            text: "     TODO: this is TODO",
            errors: [
                {
                    message: "Found TODO: 'TODO: this is TODO'"
                }
            ]
        },
```
```
    √ TODO: this is TODO (48ms)
    1)      TODO: this is TODO
```

Is this a bug or feature?
Thanks

node.js: 16.17.0
textlint: 12.2.3

**Comment by azu** [comment]
It is caused by rule implementation.
https://github.com/textlint-rule/textlint-rule-no-todo/blob/33af9e041da1e3a62a6a231a79af69995da2bfac/src/no-todo.js#L26
textlint-rule-no-todo match `/todo/i`
so, it does not match whitespace of "     TODO: this is TODO"

```
"     TODO: this is TODO",
      ^^^^
```

**Comment by er-ri** [comment]
Thanks for your response.
I tested the regular expression on https://regex101.com/, 'todo:' with leading space seems worked.

However, by debugging the textlint rule, the issue is that the string has never been passed to the program.
Can you have a look at my code? [here](https://github.com/er-ri/textlint-rule-personal-original) 
I added a line to output every text before processing, but the first test string  '         string contains 'todo' with leading spaces.' has never been printed.
```nodejs
    return {
        [Syntax.Paragraph](node) {
            const text = getSource(node);
            
            console.log("The text to be proceed: " + text);
...
```

![image](https://user-images.githubusercontent.com/50995184/207519748-46e5de10-57cd-42a8-b47b-db1eb1802a66.png)

**Comment by azu** [comment]
`   text` will be codeblock in Markdown.

   text

**Comment by er-ri** [comment]
Thank you so much! I really appreciate it! @azu
