### ISSUE TITLE
Migrate assert to invariant function

### ISSUE THREAD

**Issue by azu** [textlint/textlint#985]
We want to reduces deps in @textlint/kernel.

Node.js `assert` is extra dependencies for browser.
https://github.com/search?q=repo%3Atextlint%2Ftextlint+assert+path%3A%2F%5Epackages%5C%2F%40textlint%5C%2Fkernel%5C%2F%2F+path%3A%2F%5Epackages%5C%2F%40textlint%5C%2Fkernel%5C%2Fsrc%5C%2F%2F&type=code&l=packages%2F%40textlint%2Fkernel%2Fsrc%2F

So, We use `invariant` instead of `assert.ok` in kernel.

```ts
function invariant(condition: any, message: string): asserts condition {
    if (condition) {
        return;
    }
    throw new Error(message);
}

```

**Comment by Sean0628** [comment]
@azu Are you working on this issue?  If not, do you mind if I take up this issue?

**Comment by azu** [comment]
I haven't started working on it yet.

> If not, do you mind if I take up this issue?

Nice, I change assign to you.

📝 #986 is merged. it may will conflict.

**Comment by Sean0628** [comment]
Thanks for the quick reply. 

Let me confirm to make sure that I am understanding this right before tackling this.
So, `assert.ok` should be replaced with a new function (like `invariant`) to reduce an extra dependency on assert module right?
I see assert is used in some test files too, but these can be left untouched right?

**Comment by azu** [comment]
You do not need to change the test file.
This issue target is `src/*`.
It means that we want to move `node:assert` to devDependencies.
